
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Blob;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.imageio.ImageIO;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Se STRANGE W
 */
public class frmAccused extends javax.swing.JFrame {
Connection conn = null;//name of intialized conn
    PreparedStatement pst = null;
    ResultSet rs = null;
    private String Gender;
    
    private ImageIcon format=null;// for image load 
String filename=null;//for attaching images 
int s=0;
byte[]person_image=null;
    /**
     * Creates new form frmAccused
     */
//public String[]getdata=new String[1];
//frmAccomplisher first;
//frmAccomplisher f
    public frmAccused() {
        initComponents();
        
        
        txtAge.setVisible(false);
        
        //AutoIncre();
        
       //first=f;
        conn = DatabaseConnection.ConnecrDb();
        
        GenderSelect = new ButtonGroup();
        GenderSelect.add(Male);
        GenderSelect.add(Female);
        
        jDateChooser_DOB.getJCalendar().setMaxSelectableDate(new Date());
        
        txtSearch.setVisible(false);
    }

    
    
    //public void postData()
   // {
    //    this.txtAccomplisherID.setText("txtAccusedID"+getdata[0]);
   // }
    
    

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderSelect = new javax.swing.ButtonGroup();
        jPanel4 = new javax.swing.JPanel();
        lblTopBar = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        clear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnSearch = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblFName = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblSize1 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        txtMName = new javax.swing.JTextField();
        lblRace = new javax.swing.JLabel();
        lblMName = new javax.swing.JLabel();
        lblAccusedId1 = new javax.swing.JLabel();
        lblHeight1 = new javax.swing.JLabel();
        txtMotherName = new javax.swing.JTextField();
        lblSize = new javax.swing.JLabel();
        btnAttach = new javax.swing.JButton();
        lblMotherName = new javax.swing.JLabel();
        lblFName1 = new javax.swing.JLabel();
        lblMName1 = new javax.swing.JLabel();
        txtFatherName = new javax.swing.JTextField();
        txtSize = new javax.swing.JTextField();
        txtAccusedID = new javax.swing.JTextField();
        txtHeight = new javax.swing.JTextField();
        lblAccusedId = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        lblSkinColour = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        txtNickName = new javax.swing.JTextField();
        txtSkinColour = new javax.swing.JTextField();
        lblFatherName = new javax.swing.JLabel();
        path = new javax.swing.JTextField();
        lblLName1 = new javax.swing.JLabel();
        cboEyeColour = new javax.swing.JComboBox();
        txtOccupation = new javax.swing.JTextField();
        lblHeight = new javax.swing.JLabel();
        cboHairColour = new javax.swing.JComboBox();
        cboRace = new javax.swing.JComboBox();
        cboStatus = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        l = new javax.swing.JLabel();
        jDateChooser_DOB = new com.toedter.calendar.JDateChooser();
        jButton3 = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        photo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("SUSPECT REGISTER");
        setResizable(false);

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));
        jPanel4.setToolTipText("");

        lblTopBar.setBackground(new java.awt.Color(150, 158, 153));
        lblTopBar.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTopBar.setForeground(new java.awt.Color(255, 255, 255));
        lblTopBar.setText("Suspect Person Register ");

        jPanel2.setBackground(new java.awt.Color(150, 158, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon("C:\\CrpdasSystem\\images\\icons\\edit-file-icon.png")); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_icon.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete1.jpg"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(150, 158, 153));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 102))); // NOI18N

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Use Suspect ID to Search");

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search-icon.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSearch)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(150, 158, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Suspect  Person Details ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 18), new java.awt.Color(0, 0, 255))); // NOI18N

        lblFName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFName.setText("FIRST NAME:");

        txtAge.setText("32");
        txtAge.setToolTipText("");

        lblSize1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSize1.setText("EYE COLOUR:");

        txtFName.setToolTipText("type Alpbets only");
        txtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFNameKeyTyped(evt);
            }
        });

        txtMName.setToolTipText("type Alpbets only");
        txtMName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMNameKeyTyped(evt);
            }
        });

        lblRace.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblRace.setText("RACE:");

        lblMName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMName.setText("MIDDLE NAME:");

        lblAccusedId1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAccusedId1.setText("NICKNAME:");

        lblHeight1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHeight1.setText("AGE");

        txtMotherName.setToolTipText("type Alpbets only");
        txtMotherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtMotherNameKeyTyped(evt);
            }
        });

        lblSize.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSize.setText("SIZE:");

        btnAttach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAttach.setIcon(new javax.swing.ImageIcon("C:\\Users\\Se STRANGE W\\Documents\\NetBeansProjects\\CRIME MANAGEMENT INFORMATION SYSTEM\\images\\icons\\Attach.png")); // NOI18N
        btnAttach.setText("Attach Photo");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        lblMotherName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMotherName.setText("MOTHER'S NAME:");

        lblFName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFName1.setText("HAIR COLOUR:");

        lblMName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblMName1.setText("STATUS");

        txtFatherName.setToolTipText("type Alpbets only");
        txtFatherName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFatherNameKeyTyped(evt);
            }
        });

        txtSize.setToolTipText("Type Numbers only");
        txtSize.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSizeKeyTyped(evt);
            }
        });

        txtAccusedID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccusedIDKeyTyped(evt);
            }
        });

        txtHeight.setToolTipText("Typo Numbers only(Height is Metres)");
        txtHeight.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtHeightKeyTyped(evt);
            }
        });

        lblAccusedId.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblAccusedId.setText("SUSPECT ID:");

        txtLName.setToolTipText("type Alpbets only");
        txtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLNameKeyTyped(evt);
            }
        });

        lblSkinColour.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSkinColour.setText("SKIN COLOUR:");

        lblLName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLName.setText("LAST NAME:");

        txtNickName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNickNameKeyTyped(evt);
            }
        });

        txtSkinColour.setToolTipText("type Alpbets only");
        txtSkinColour.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSkinColourKeyTyped(evt);
            }
        });

        lblFatherName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFatherName.setText("FATHER'S NAME:");

        lblLName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLName1.setText("OCCUPATION:");

        cboEyeColour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Blue", "Gray", "Bluish-green", "Gray-Blue", "Green", "dark brown", " " }));

        txtOccupation.setToolTipText("type Alpabets only");
        txtOccupation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtOccupationKeyTyped(evt);
            }
        });

        lblHeight.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblHeight.setText("HEIGHT:");

        cboHairColour.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black", "Brown", "Red", "Blonde", "Auburn ", "Chestnut ", " Gray ", "White" }));

        cboRace.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Black ", "African American", "Indian", "Asian", " " }));

        cboStatus.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Alive", "Dead" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("GENDER");

        Female.setText("FEMALE");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });

        Male.setText("MALE");
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        l.setText("DOB");

        jDateChooser_DOB.setDateFormatString("yyyy-MM-dd");

        jButton3.setBackground(new java.awt.Color(0, 0, 204));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(255, 255, 255));
        jButton3.setText("Accomplisher Form Fill");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1.setLayer(photo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Metres");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("Kgs");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSkinColour)
                    .addComponent(lblRace)
                    .addComponent(lblSize)
                    .addComponent(lblHeight)
                    .addComponent(lblMotherName)
                    .addComponent(lblFatherName)
                    .addComponent(lblLName)
                    .addComponent(lblMName)
                    .addComponent(lblFName)
                    .addComponent(lblAccusedId)
                    .addComponent(lblAccusedId1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboRace, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNickName)
                            .addComponent(txtFName)
                            .addComponent(txtAccusedID)
                            .addComponent(txtMName)
                            .addComponent(txtLName)
                            .addComponent(txtFatherName)
                            .addComponent(txtMotherName)
                            .addComponent(txtSkinColour)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtSize, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE)
                                    .addComponent(txtHeight, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(9, 9, 9)
                                        .addComponent(jLabel3))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel4)))))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblHeight1)
                                    .addComponent(lblLName1)
                                    .addComponent(lblMName1)
                                    .addComponent(lblFName1)
                                    .addComponent(l))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lblSize1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cboEyeColour, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jDateChooser_DOB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 181, Short.MAX_VALUE)
                            .addComponent(txtOccupation, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtAge, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cboHairColour, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cboStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jButton3)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(btnAttach, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)))
                                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 34, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Male)
                        .addGap(45, 45, 45)
                        .addComponent(Female)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAccusedId)
                            .addComponent(txtAccusedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFName)
                            .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMName)
                            .addComponent(txtMName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblLName)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblFatherName)
                            .addComponent(txtFatherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMotherName)
                            .addComponent(txtMotherName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHeight)
                            .addComponent(txtHeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSize)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboRace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRace)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton3)
                        .addGap(3, 3, 3)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jDateChooser_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblFName1)
                                            .addComponent(cboHairColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(21, 21, 21)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblMName1)
                                            .addComponent(cboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(22, 22, 22)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(lblLName1)
                                            .addComponent(txtOccupation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHeight1)
                                    .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnAttach)
                                    .addComponent(l))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cboEyeColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSize1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Male)
                            .addComponent(Female))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSkinColour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSkinColour))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNickName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAccusedId1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Please fill missing values with a Null or -");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(lblTopBar, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(281, 281, 281))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblTopBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(63, 63, 63)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1085, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
        
          JFileChooser chooser=new JFileChooser();
       chooser.showOpenDialog(null);
       File f= chooser.getSelectedFile();
       
       filename=f.getAbsolutePath();// declared at bottom to make the string filename global variable 
       path.setText(filename);
       
       
        Icon icon = new ImageIcon(filename);
            
            photo.setIcon(icon);
       
       try
       { 
           //This convert the image into byte which is later saved into the variable person_image 
           File image = new File(filename);
           FileInputStream fis= new FileInputStream(image);
           
           ByteArrayOutputStream bos=new ByteArrayOutputStream();
           byte[] buf= new byte [1024];
           
           for(int readNum;(readNum=fis.read(buf))!=-1;)
           {
               bos.write(buf,0,readNum);
           }
           
            person_image=bos.toByteArray();//variable for saving image into 
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
        
        
    }//GEN-LAST:event_btnAttachActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        
          if(txtAccusedID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Accused Id","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtAccusedID.requestFocus();
            
        }
        else  if(txtFName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Frist  Name ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            txtFName.requestFocus();
            
            
            
        }
         else  if(txtMName.getText().equals("")||txtLName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Middle Name   ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            txtMName.requestFocus();
           
        }
          else  if(txtLName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter   Last Name  ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            txtMName.requestFocus();
           
        }
         
         else  if(txtFatherName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Suspects Father Name  ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            txtFatherName.requestFocus();
           
        }
         
         
          else  if(txtMotherName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Mothers Name  ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            txtMotherName.requestFocus();
           
        }
         
          else  if( txtHeight.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Height ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtHeight.requestFocus();
           
        }
          else  if( txtSize.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Size in Kg ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtSize.requestFocus();
           
        }
          else  if( txtNickName.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the  NickName ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtNickName.requestFocus();
           
        }
         else  if( txtOccupation.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the  Occupation ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtOccupation.requestFocus();
           
         }
         
      /*   else  if( txtCriminalNo.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the  Criminal Number ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtCriminalNo.requestFocus();
           
         }*/
          
        else  if( path.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Select  a picture from files  ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            //txtCriminalNo.requestFocus();
            
            
           
         }
          
          
          else  if( jDateChooser_DOB.getDate()==null  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Select Date of  Birth  ","CRPDAS   Message",JOptionPane.INFORMATION_MESSAGE);
            jDateChooser_DOB.requestFocus();
           
        }
         
       
        
          
        else
         {
        
         try {
            String sql = "Insert  into accused(Accused_ID,FName,SName,LName,FatherName,MotherName,Height,Size,Race,Skin_Colour,Hair_Colour,Status,Nickname,Occupation,Age,DOB,Eye_Colour,Gender,photo)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);

            pst.setString(1, txtAccusedID.getText());
            pst.setString(2, txtFName.getText());
            pst.setString(3, txtMName.getText());
            pst.setString(4, txtLName.getText());
            pst.setString(5, txtFatherName.getText());
            pst.setString(6, txtMotherName.getText());
            pst.setString(7, txtHeight.getText());
            pst.setString(8, txtSize.getText());
            String value=cboRace.getSelectedItem().toString();//ComboBox 
            pst.setString(9, value);
            
            pst.setString(10, txtSkinColour.getText());
            String value2=cboHairColour.getSelectedItem().toString();//ComboBox 
            pst.setString(11, value2);
           String value3=cboStatus.getSelectedItem().toString();//ComboBox 
            pst.setString(12, value3);
             pst.setString(13, txtNickName.getText());
            
            pst.setString(14, txtOccupation.getText());
           /* String value4=cboCrimeType.getSelectedItem().toString();//ComboBox 
            pst.setString(15, value4);
            
            pst.setString(16, txtCriminalNo.getText());*/
            pst.setString(15, txtAge.getText());
            
             pst.setString(16, ((JTextField)jDateChooser_DOB.getDateEditor().getUiComponent()).getText());
            String value5=cboEyeColour.getSelectedItem().toString();//ComboBox 
            pst.setString(17, value5);
            
            pst.setString(18, Gender);
         
            
            pst.setBytes(19,person_image);//takes the image from the viarable declared in the form
            

            pst.execute();

            JOptionPane.showMessageDialog(null, "Saved Succesfully");
        } 
          catch (SQLException er) {
            
            JOptionPane.showMessageDialog(null,er);
        }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

            if(txtAccusedID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Type The Accused Id you want to delete ");
        }
        else{
        
        
        int n=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete","CRPDAS",JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION)
        {
        
        
         String sql = "delete from accused where Accused_ID=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtAccusedID.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        }
        
            }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed

        Gender="Female";
    }//GEN-LAST:event_FemaleActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        Gender="Male";
    }//GEN-LAST:event_MaleActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
       
       
        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        txtAccusedID.setText("");
        txtFName.setText("");
        txtMName.setText("");
        txtLName.setText("");
        txtFatherName.setText("");
       
        txtMotherName.setText("");
        txtHeight.setText("");
        txtSize.setText("");
        //cboRace.setText("");
        txtSkinColour.setText("");
        txtNickName.setText("");
        txtOccupation.setText("");
        
        txtAge.setText("");
        path.setText("");
        
    }//GEN-LAST:event_clearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       
        frmAccomplisher nf1 = new frmAccomplisher();
        frmAccomplisher.txtAccusedId.setText(this.txtAccusedID.getText());
        nf1.setVisible(true);
        
        
        
      /*jPanel5.getdata[0]=this.txtAccusedID.getText();
        first.postData();
        this.setVisible(false);*/
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
         if(txtAccusedID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Accused Id","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtAccusedID.requestFocus();
            
        }
        else  if(txtFName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Frist  Name ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            txtFName.requestFocus();
            
            
            
        }
         else  if(txtMName.getText().equals("")||txtLName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Middle Name   ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            txtMName.requestFocus();
           
        }
          else  if(txtLName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter   Last Name  ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            txtMName.requestFocus();
           
        }
         
         else  if(txtFatherName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Suspects Father Name  ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            txtFatherName.requestFocus();
           
        }
         
         
          else  if(txtMotherName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Mothers Name  ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            txtMotherName.requestFocus();
           
        }
         
          else  if( txtHeight.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Height ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtHeight.requestFocus();
           
        }
          else  if( txtSize.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Size in Kg ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtSize.requestFocus();
           
        }
          else  if( txtNickName.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the  NickName ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtNickName.requestFocus();
           
        }
         else  if( txtOccupation.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the  Occupation ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtOccupation.requestFocus();
           
         }
         
        
          
        
          
          
          else  if( jDateChooser_DOB.getDate()==null  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Select Date of  Birth  ","CRPDAS   Message",JOptionPane.INFORMATION_MESSAGE);
            jDateChooser_DOB.requestFocus();
           
        }
         
       
        
          
        else
         {
        
         try {

            String value1 = txtAccusedID.getText();
            String value2 = txtFName.getText();
            String value3 = txtMName.getText();
            String value4 = txtLName.getText();
            String value5 = txtFatherName.getText();
            String value6 = txtMotherName.getText();
            String value7 = txtHeight.getText();
            String value8 = txtSize.getText();
            
            String value9=cboRace.getSelectedItem().toString();
            String value10=txtSkinColour.getText();
            String value11=cboHairColour.getSelectedItem().toString();
            String value12=cboStatus.getSelectedItem().toString(); 
            String value13 = txtNickName.getText();
               
            
            String value14 = txtOccupation.getText();
            //String value15=cboCrimeType.getSelectedItem().toString(); 
            //String value16 = txtCriminalNo.getText();
            
            String value17 = txtAge.getText();//d/d/dd
            
            
            
            //value18 date;
                       
            // pst.setString(18, ((JTextField)jDateChooser_DOB.getDateEditor().getUiComponent()).getText());
             String value18=((JTextField)jDateChooser_DOB.getDateEditor().getUiComponent()).getText();
             
            String value19=cboEyeColour.getSelectedItem().toString();
            
            
            
            
            
             String searchn = txtSearch.getText();
              pst.setBytes(5,person_image);
            

            String sql = "update accused set Accused_ID='" + value1 + "',Fname='" + value2 + "',SName='" + value3 + "',Lname='" + value4 + "',FatherName='" + value5 + "',MotherName='" + value6 + "',Height='" + value7 + "',Size='" + value8 + "',Race='" + value9 + "',"
                    + "Skin_Colour='" + value10 + "',Hair_Colour='" + value11 + "',Status='" + value12 + "',Nickname='" + value13 + "',Occupation='" + value14 + "',Age='" + value17 + "',DOB='" + value18 + "',Eye_Colour ='" + value19 + "'  where Accused_ID='" + searchn + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
         }
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        if(txt_search.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Suspect's  ID to search","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txt_search.requestFocus();
        }
        else 
        {
        
         try {
            String sql = "select * from   accused where Accused_ID =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText());

            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("Accused_ID");
                txtAccusedID.setText(add1);
                String add2 = rs.getString("FName");
                txtFName.setText(add2);
                String add3 = rs.getString("SName");
                txtMName.setText(add3);
                String add4 = rs.getString("LName");
                txtLName.setText(add4);
                String add5 = rs.getString("FatherName");
                txtFatherName.setText(add5);
                String add6 = rs.getString("MotherName");
                txtMotherName.setText(add6);
                String add7 = rs.getString("Height");
                txtHeight.setText(add7);
                String add8 = rs.getString("Size");
                txtSize.setText(add8);
                String pat = rs.getString("Race");
                   cboRace.addItem(pat);
                String add10 = rs.getString("Skin_Colour");
                txtSkinColour.setText(add10);
                String add11 = rs.getString("Hair_Colour");
                txtNickName.setText(add11);
                String pat2 = rs.getString("Status");
                   cboHairColour.addItem(pat2);
                
                   String addNick=rs.getString("Nickname");
                   txtNickName.setText(addNick);
                   
                 String add13=rs.getString("Occupation");
                   txtOccupation.setText(add13);
                 /*String pat4=rs.getString("Crime_Type");
                 cboCrimeType.addItem(pat4);
                 String add14=rs.getString("CriminalNo");
                 txtCriminalNo.setText(add14);*/
                 String add15=rs.getString("Age");
                 txtAge.setText(add15);
                 
                 
                  String dateValue = rs.getString("DOB"); // What ever column
                java.util.Date add16 = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                jDateChooser_DOB.setDate(add16);
                
                String pat5=rs.getString("Eye_Colour");
                cboEyeColour.addItem(pat5);
                
                
                 String  txtSearchg = rs.getString("Accused_ID");
                txtSearch.setText(txtSearchg);
                
                
                
                 String add18 = rs.getString("Gender");
                 if (add5.equals("Female")){
                  Male.setSelected(false);
                 Female.setSelected(true);
                 } else {
                 Female.setSelected(false);
                 Male.setSelected(true);
                 }               
               
                 
                 byte[]imagedata=rs.getBytes("photo");
                ImageIcon imageicon= new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(photo.getWidth(),photo.getHeight(),Image.SCALE_DEFAULT));
               // format=new ImageIcon(imagedata);
                photo.setIcon(imageicon);
                  

            }
             else
            {
                JOptionPane.showMessageDialog(null,"The Record has not been found","CRPDAS MEssage",JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtAccusedIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccusedIDKeyTyped
        // TODO add your handling code here:
        
        
        if(   (!(Character.isDigit(evt.getKeyChar()))) &&  (!(Character.isSpaceChar(evt.getKeyChar()))) && (evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)  &&(evt.getKeyChar()!=KeyEvent.VK_DELETE)&& (evt.getKeyChar()!=KeyEvent.VK_ESCAPE)  )
        {
            evt.consume();
            
           JOptionPane.showMessageDialog(null, "Numbers only  i.e 0-9","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            
            
        
        }
         
        boolean max= txtAccusedID.getText().length()>15;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtAccusedIDKeyTyped

    private void txtFNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNameKeyTyped
        // TODO add your handling code here:
        
         if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
        
         boolean max= txtFName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtFNameKeyTyped

    private void txtMNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMNameKeyTyped
        // TODO add your handling code here:
         boolean max= txtMName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        }
        
          if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
    }//GEN-LAST:event_txtMNameKeyTyped

    private void txtLNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtLName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        }
        
          if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
    }//GEN-LAST:event_txtLNameKeyTyped

    private void txtFatherNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFatherNameKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtFatherName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
          if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
    }//GEN-LAST:event_txtFatherNameKeyTyped

    private void txtMotherNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMotherNameKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtMotherName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        }
        
          if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
    }//GEN-LAST:event_txtMotherNameKeyTyped

    private void txtHeightKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtHeightKeyTyped
 boolean max= txtHeight.getText().length()>6;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        }    
          if(   (!(Character.isDigit(evt.getKeyChar()))) &&  (!(Character.isSpaceChar(evt.getKeyChar()))) && (evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)  &&(evt.getKeyChar()!=KeyEvent.VK_DELETE)&& (evt.getKeyChar()!=KeyEvent.VK_ESCAPE)  )
        {
            evt.consume();
            
           JOptionPane.showMessageDialog(null, "Numbers only  i.e 0-9","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            
            
        
        }
        
// TODO add your handling code here:
    }//GEN-LAST:event_txtHeightKeyTyped

    private void txtSizeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSizeKeyTyped
        // TODO add your handling code here:
        
        
        boolean max= txtSize.getText().length()>6;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        }   
        
        
        
          if(   (!(Character.isDigit(evt.getKeyChar()))) &&  (!(Character.isSpaceChar(evt.getKeyChar()))) && (evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)  &&(evt.getKeyChar()!=KeyEvent.VK_DELETE)&& (evt.getKeyChar()!=KeyEvent.VK_ESCAPE)  )
        {
            evt.consume();
            
           JOptionPane.showMessageDialog(null, "Numbers only  i.e 0-9","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            
            
        
        }
    }//GEN-LAST:event_txtSizeKeyTyped

    private void txtSkinColourKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSkinColourKeyTyped
        // TODO add your handling code here:
        
        boolean max= txtSkinColour.getText().length()>10;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        } 
        
          if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
    }//GEN-LAST:event_txtSkinColourKeyTyped

    private void txtNickNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNickNameKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtNickName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        } 
        
        
        
          if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
    }//GEN-LAST:event_txtNickNameKeyTyped

    private void txtOccupationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOccupationKeyTyped
        // TODO add your handling code here:
        
        boolean max= txtOccupation.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        } 
        
        
          if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
    }//GEN-LAST:event_txtOccupationKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAccused.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAccused.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAccused.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAccused.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAccused().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Female;
    private javax.swing.ButtonGroup GenderSelect;
    private javax.swing.JRadioButton Male;
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cboEyeColour;
    private javax.swing.JComboBox cboHairColour;
    private javax.swing.JComboBox cboRace;
    private javax.swing.JComboBox cboStatus;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser_DOB;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel l;
    private javax.swing.JLabel lblAccusedId;
    private javax.swing.JLabel lblAccusedId1;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblFName1;
    private javax.swing.JLabel lblFatherName;
    private javax.swing.JLabel lblHeight;
    private javax.swing.JLabel lblHeight1;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblLName1;
    private javax.swing.JLabel lblMName;
    private javax.swing.JLabel lblMName1;
    private javax.swing.JLabel lblMotherName;
    private javax.swing.JLabel lblRace;
    private javax.swing.JLabel lblSize;
    private javax.swing.JLabel lblSize1;
    private javax.swing.JLabel lblSkinColour;
    private javax.swing.JLabel lblTopBar;
    private javax.swing.JTextField path;
    private javax.swing.JLabel photo;
    public static javax.swing.JTextField txtAccusedID;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtFatherName;
    private javax.swing.JTextField txtHeight;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtMName;
    private javax.swing.JTextField txtMotherName;
    private javax.swing.JTextField txtNickName;
    private javax.swing.JTextField txtOccupation;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSize;
    private javax.swing.JTextField txtSkinColour;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

    void setVisibleTrue(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
