
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Se STRANGE W
 */
public class frmAccomplisher extends javax.swing.JFrame {

    Connection conn = null;//name of intialized conn
    PreparedStatement pst = null;
    ResultSet rs = null;
    public String[]getdata=new String[1];
    
    
     private ImageIcon format=null;// for image load 
      String filename=null;//for attaching images 
//int s=0;
byte[]person_image=null;// for insert 


byte[]image_update=null;//for update 


    /**
     * Creates new form frmAccused
     */
//public String[]getdata=new String[1];
    /**
     * Creates new form frmAccomplisher
     */
    public frmAccomplisher() {
        initComponents();
        
        conn = DatabaseConnection.ConnecrDb();
        
        txtSearch.setVisible(false);
        path.setVisible(false);
    }
    
    private void clean()
    {
        txtAccomplisherID.setText("");
        txtAccusedId.setText("");
        txtFName.setText("");
        txtSName.setText("");
        path.setText("");
    }

    public void postData()
    {
        this.txtAccomplisherID.setText("txtAccusedID"+getdata[0]);
    }
    
    
    public void updateImage()
    {
         try
         {
        filename=image.getIcon().toString();
               File image = new File(filename);
           FileInputStream fis= new FileInputStream(image);
           
           ByteArrayOutputStream bos=new ByteArrayOutputStream();
           byte[] buf= new byte [1024];
           
           for(int readNum;(readNum=fis.read(buf))!=-1;)
           {
               bos.write(buf,0,readNum);
           }
          //   image_update=bos.toByteArray();
             
        }
         
         catch(Exception ex)
         {
              JOptionPane.showMessageDialog(null,"The Image does not exist");
         }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        path = new javax.swing.JTextField();
        txtSearch = new javax.swing.JTextField();
        jPanel_Properties1 = new javax.swing.JPanel();
        lblSearch1 = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        txtFName = new javax.swing.JTextField();
        txtSName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtAccusedId = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtAccomplisherID = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        image = new javax.swing.JLabel();
        Attach = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ACCOMPLISHER REGISTER");

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        jPanel_Properties1.setBackground(new java.awt.Color(150, 158, 153));
        jPanel_Properties1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        lblSearch1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSearch1.setText("Please Type Accomplisher Id to Search");

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon("C:\\CrpdasSystem\\images\\icons\\Search-icon.png")); // NOI18N
        jButton3.setText("Search");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Properties1Layout = new javax.swing.GroupLayout(jPanel_Properties1);
        jPanel_Properties1.setLayout(jPanel_Properties1Layout);
        jPanel_Properties1Layout.setHorizontalGroup(
            jPanel_Properties1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblSearch1)
            .addGroup(jPanel_Properties1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3))
        );
        jPanel_Properties1Layout.setVerticalGroup(
            jPanel_Properties1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Properties1Layout.createSequentialGroup()
                .addComponent(lblSearch1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_Properties1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        jLabel6.setBackground(new java.awt.Color(150, 158, 153));
        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Accomplisher Register ");

        jPanel2.setBackground(new java.awt.Color(150, 158, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\CrpdasSystem\\images\\icons\\clear.png")); // NOI18N
        jButton1.setText("CLEAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon("C:\\CrpdasSystem\\images\\icons\\edit-file-icon.png")); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_icon.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete1.jpg"))); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnDelete)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(150, 158, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, " Accomplisher Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.setForeground(new java.awt.Color(255, 255, 255));

        txtFName.setToolTipText("Enter Alphabets only");
        txtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFNameKeyTyped(evt);
            }
        });

        txtSName.setToolTipText("Enter alphabets only");
        txtSName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSNameKeyTyped(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("SECOND NAMES:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("ACCOMPLISHER ID:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Suspect ID:");

        txtAccusedId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccusedIdKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("FIRST NAME:");

        txtAccomplisherID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccomplisherIDKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 153));
        jLabel5.setText("PHOTO");

        image.setText("Image");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(image, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                .addContainerGap())
        );
        jDesktopPane1.setLayer(image, javax.swing.JLayeredPane.DEFAULT_LAYER);

        Attach.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        Attach.setIcon(new javax.swing.ImageIcon("C:\\Users\\Se STRANGE W\\Documents\\NetBeansProjects\\CRIME MANAGEMENT INFORMATION SYSTEM\\images\\icons\\Attach.png")); // NOI18N
        Attach.setText("Attach Picture");
        Attach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AttachActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("LAST NAME");

        txtLastName.setToolTipText("enter alphabets only");
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLastNameKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtAccomplisherID, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                            .addComponent(txtAccusedId)
                            .addComponent(txtFName)
                            .addComponent(txtSName)))
                    .addComponent(Attach)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(73, 73, 73))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5)
                    .addComponent(txtAccomplisherID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(txtAccusedId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Attach))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44))))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(173, 173, 173)
                                .addComponent(jLabel6))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(33, 33, 33)
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jPanel_Properties1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel_Properties1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(211, 211, 211)
                                .addComponent(path, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(753, 411));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        

        clean();

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed

         if(txtAccomplisherID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Accomplisher ID","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtAccomplisherID.requestFocus();
            
        }
        else  if(txtFName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter First Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtFName.requestFocus();
            
            
            
        }
         else  if(txtSName.getText().equals("")|| txtLastName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Middle Name or Last  Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtSName.requestFocus();
           
        }
         
          else  if( path.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Select a Picture   Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtSName.requestFocus();
           
        }
         
         
        
          
        else
         {
        
        try {
            String sql = "Insert  into accomplisher(Accomplisher_id,Fname,Sname,Lname,photo,Accused_id)values(?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);

            pst.setString(1, txtAccomplisherID.getText());
            pst.setString(2, txtAccusedId.getText());
            pst.setString(3, txtFName.getText());
            pst.setString(4, txtSName.getText());
             pst.setBytes(5,person_image);
            pst.setString(6,txtLastName.getText());
            
           
           

            pst.execute();
            
            clean();

            JOptionPane.showMessageDialog(null, "Saved Succesfully");
        } 
         catch (SQLException er) {
            
            JOptionPane.showMessageDialog(null, "The Record is already Saved you cannot save it again","CRPDS Message",JOptionPane.INFORMATION_MESSAGE);
        }
        
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         }
        
        
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if(txtAccomplisherID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Type The Case Id you want to delete ");
        }
        else{
        
        
        int n=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete","CRPDAS",JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION)
        {
            
        String sql = "delete from accomplisher where txtAccomplisherID=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtAccomplisherID.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        
        clean();
        }
        
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void AttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AttachActionPerformed
        // TODO add your handling code here:
       JFileChooser chooser=new JFileChooser();
       chooser.showOpenDialog(null);
       File f= chooser.getSelectedFile();
       
       filename=f.getAbsolutePath();// declared at bottom to make the string filename global variable 
       path.setText(filename);
       
       
           Icon icon = new ImageIcon(filename);
            
            image.setIcon(icon);
            
            
            // filename=f.getAbsolutePath();
            
            
       
       
       try
       { 
           //This convert the image into byte which is later saved into the variable person_image 
           File image = new File(filename);
           FileInputStream fis= new FileInputStream(image);
           
           ByteArrayOutputStream bos=new ByteArrayOutputStream();
           byte[] buf= new byte [1024];
           
           for(int readNum;(readNum=fis.read(buf))!=-1;)
           {
               bos.write(buf,0,readNum);
           }
           
            person_image=bos.toByteArray();//variable for saving image into 
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
        
    }//GEN-LAST:event_AttachActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        
// TODO add your handling code here:
         if(txtAccomplisherID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Accomplisher ID","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtAccomplisherID.requestFocus();
            
        }
        else  if(txtFName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter First Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtFName.requestFocus();
            
            
            
        }
         else  if(txtSName.getText().equals("")|| txtLastName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Middle Name or Last  Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtSName.requestFocus();
           
        }
         
          else  if( image.getText().isEmpty()  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Select a Picture   Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
           // txtSName.requestFocus();
           
          }
         
         
        
          
        else
         {
          try {

            String value1 = txtAccomplisherID.getText();
            String value2 = txtAccusedId.getText();
            String value3 = txtFName.getText();
            String value4 = txtSName.getText();
            String value5 = txtLastName.getText();
            
            
             String searchn = txtSearch.getText();
             // String value6=Arrays.toString(person_image);
              
              // pst.setBytes(5,person_image);
             
             
               String value6=Arrays.toString(image_update);
              
              //set Jlabel photo to the update.
            

            String sql = "update accomplisher set Accomplisher_id='" + value1 + "',Accused_id='" + value2 + "',Fname='" + value3 + "',Sname='" + value4 + "',Lname='" + value5 + "',photo='" + value6 + "' where Accomplisher_id='" + searchn + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
         }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased

        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyTyped

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
         if(txt_search.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Accomplisher  ID to search","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txt_search.requestFocus();
        }
        else 
        {
        
        try {
            String sql = "select * from  accomplisher where Accomplisher_id=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText());

            rs = pst.executeQuery();
            
            if (rs.next()) {
                String add1 = rs.getString("Accomplisher_id");
                txtAccomplisherID.setText(add1);
                String add2 = rs.getString("Fname");
                txtFName.setText(add2);
                String add3 = rs.getString("Sname");
                txtSName.setText(add3);
                String add4 = rs.getString("Lname");
                txtLastName.setText(add4);
                String add5 = rs.getString("Accused_id");
                txtAccusedId.setText(add5);
                
               /* byte[]imagedata=rs.getBytes("photo");
                ImageIcon imageicon= new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(image.getWidth(),image.getHeight(),Image.SCALE_DEFAULT));
                image.setIcon(imageicon);*/
                
                 byte[]imagedata=rs.getBytes("photo");
                ImageIcon imageicon= new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(image.getWidth(),image.getHeight(),Image.SCALE_DEFAULT));
               // format=new ImageIcon(imagedata);
                image.setIcon(imageicon);
                
                
                
                String searched = rs.getString("Accomplisher_id");
                txtSearch.setText(searched);

            }
             else
            {
                JOptionPane.showMessageDialog(null,"The Record has not been found","CRPDAS MEssage",JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtAccomplisherIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccomplisherIDKeyTyped
        // TODO add your handling code here:
        
         if(   (!(Character.isDigit(evt.getKeyChar()))) &&  (!(Character.isSpaceChar(evt.getKeyChar()))) && (evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)  &&(evt.getKeyChar()!=KeyEvent.VK_DELETE)&& (evt.getKeyChar()!=KeyEvent.VK_ESCAPE)  )
        {
            evt.consume();
            
           JOptionPane.showMessageDialog(null, "Numbers only  i.e 0-9","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            
            
        
        }
         
        boolean max= txtAccomplisherID.getText().length()>15;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtAccomplisherIDKeyTyped

    private void txtAccusedIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccusedIdKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtAccusedId.getText().length()>15;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        if(   (!(Character.isDigit(evt.getKeyChar()))) &&  (!(Character.isSpaceChar(evt.getKeyChar()))) && (evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)  &&(evt.getKeyChar()!=KeyEvent.VK_DELETE)&& (evt.getKeyChar()!=KeyEvent.VK_ESCAPE)  )
        {
            evt.consume();
            
           JOptionPane.showMessageDialog(null, "Numbers only  i.e 0-9","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            
            
        
        }
    }//GEN-LAST:event_txtAccusedIdKeyTyped

    private void txtFNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNameKeyTyped
        // TODO add your handling code here:
         boolean max= txtFName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
         if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
    }//GEN-LAST:event_txtFNameKeyTyped

    private void txtSNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSNameKeyTyped
        // TODO add your handling code here:
        boolean max= txtSName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
          if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
            
           JOptionPane.showMessageDialog(null, "Alphabets only","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            
            
        }
        
    }//GEN-LAST:event_txtSNameKeyTyped

    private void txtLastNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyTyped
        // TODO add your handling code here:
        
        
                
                 boolean max= txtLastName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
                
          if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
            
           JOptionPane.showMessageDialog(null, "Alphabets only","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            
            
        }
    }//GEN-LAST:event_txtLastNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmAccomplisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmAccomplisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmAccomplisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmAccomplisher.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmAccomplisher().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Attach;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Properties1;
    private javax.swing.JLabel lblSearch1;
    private javax.swing.JTextField path;
    public static javax.swing.JTextField txtAccomplisherID;
    public static javax.swing.JTextField txtAccusedId;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txt_search;
    // End of variables declaration//GEN-END:variables

    void setVisibleTrue(boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
