
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Se STRANGE W
 */
public class frmFIR extends javax.swing.JFrame {
Connection conn = null;//name of intialized conn
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
    
    /**
     * Creates new form frmFIR
     */
    public frmFIR() {
        initComponents();
        conn = DatabaseConnection.ConnecrDb();
        txtSearched.setVisible(false);
        
        txtFirrecv.setVisible(false);
        Fill_location();
        
       
                dtbFiled.getJCalendar().setMaxSelectableDate(new Date());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    private void Fill_location()
    {
        try {
            
            String sql="select * from locations";
            pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next())
            {
                String location=rs.getString("LocationName");
                cboLocation.addItem(location);
                
                        
            }
                
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        txtFIRNo = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtVictimID = new javax.swing.JTextField();
        dtbFiled = new com.toedter.calendar.JDateChooser();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTime = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtAIncedent = new javax.swing.JTextArea();
        txtSName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        txtFName = new javax.swing.JTextField();
        txtAccusedId = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        cboCrimeType = new javax.swing.JComboBox();
        cboLocation = new javax.swing.JComboBox();
        txtFirrecv = new javax.swing.JTextField();
        txtSearched = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSeacrhed = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        cmd_delete = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("OBR FORM");

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        jPanel1.setBackground(new java.awt.Color(150, 158, 153));

        txtFIRNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFIRNoKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("Last Name:");

        txtVictimID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtVictimIDKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtVictimIDKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtVictimIDKeyTyped(evt);
            }
        });

        dtbFiled.setToolTipText("Please Enter the Date in the format \"yyyy-MM-dd\"");
        dtbFiled.setDateFormatString("yyyy-MM-dd");
        dtbFiled.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dtbFiledKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setText("Date Filled:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Incident");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setText("Second Name:");

        txtTime.setToolTipText("Please Enter The time");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setText("Place of Inc./Location");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setText("Time Filed");

        txtAIncedent.setColumns(20);
        txtAIncedent.setRows(5);
        txtAIncedent.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAIncedentKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txtAIncedent);

        txtSName.setToolTipText("Enter Alphabets oinly");
        txtSName.setEnabled(false);
        txtSName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSNameKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("First Name:");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("FIR No:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Vcitim Id:");

        txtLName.setToolTipText("Enter Alphabets Only");
        txtLName.setEnabled(false);
        txtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLNameKeyTyped(evt);
            }
        });

        txtFName.setToolTipText("Enter Alphabets only");
        txtFName.setEnabled(false);
        txtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFNameKeyTyped(evt);
            }
        });

        txtAccusedId.setToolTipText("Enter either Alphabet, Numbers or both");
        txtAccusedId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtAccusedIdKeyTyped(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Suspect ID:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel14.setText("Crime Type:");

        cboCrimeType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Undefined", "Assult", "Stilling", "Homicide", "Rape", "Sexual Harrasment ", "Accident", "Riot", " " }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel5))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(txtFIRNo, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(txtVictimID, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtFName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(37, 37, 37))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel14)
                                            .addComponent(jLabel13))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSName)
                                    .addComponent(txtLName)
                                    .addComponent(txtAccusedId)
                                    .addComponent(cboCrimeType, 0, 126, Short.MAX_VALUE))))
                        .addGap(57, 57, 57)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(32, 32, 32)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtTime)
                                            .addComponent(dtbFiled, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(cboLocation, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(356, 356, 356)
                        .addComponent(txtFirrecv, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtFIRNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel3))
                            .addComponent(txtVictimID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel7))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtAccusedId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(dtbFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel9))
                            .addComponent(txtTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jLabel10))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(cboLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cboCrimeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtFirrecv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(150, 158, 153));

        btnSeacrhed.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSeacrhed.setIcon(new javax.swing.ImageIcon("C:\\CrpdasSystem\\images\\icons\\Search-icon.png")); // NOI18N
        btnSeacrhed.setText("Search");
        btnSeacrhed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeacrhedActionPerformed(evt);
            }
        });

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel16.setText("Please Use Obr No to Search");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSeacrhed)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSeacrhed)))
        );

        jPanel2.setBackground(new java.awt.Color(150, 158, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Telenor", 1, 14), new java.awt.Color(0, 0, 255))); // NOI18N

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon("C:\\CrpdasSystem\\images\\icons\\edit-file-icon.png")); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon("C:\\CrpdasSystem\\images\\icons\\Save_icon.png")); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        cmd_delete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmd_delete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete1.jpg"))); // NOI18N
        cmd_delete.setText("DELETE");
        cmd_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmd_deleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(cmd_delete, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cmd_delete))
        );

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("OBR Register");

        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Please fill missing values with a Null or -");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtSearched, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(204, 204, 204)
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel17)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(txtSearched, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(39, 39, 39)
                .addComponent(jLabel4)
                .addGap(340, 340, 340))
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed

        if(txtFIRNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter OBR Number","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtFIRNo.requestFocus();
            
        }
        else  if(txtVictimID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  victim ID","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtVictimID.requestFocus();
            
        }
        else  if(txtFName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter First Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtFName.requestFocus();
            
            
            
        }
         else  if(txtSName.getText().equals("")|| txtLName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Middle Name or Last  Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtSName.requestFocus();
           
        }
         
          else  if( txtAccusedId.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Select a Picture   Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtSName.requestFocus();
           
        }
         
          
          
            else  if(txtAIncedent.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  The Incident ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtAIncedent.requestFocus();
           
        }
            
              else  if(txtTime.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  The Time of  Incident ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtTime.requestFocus();
           
        }
            
           // else  if(((JTextField)dtbFiled.getDateEditor().getUiComponent().getText().isEmpty()) )
            
           /* else if(  try
                    {
                    
                       if( ((JTextField)dtbFiled.getDateEditor().getUiComponent().getText().isEmpty()))
                           
                       {
                                }}
                            catch(Exception ex)
                            {
                            }
                            )
                
        {
            JOptionPane.showMessageDialog(null,"Please Chooser a date ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtAIncedent.requestFocus();
           
        }*/
        
          
        else
         {
        
        try {

            String value1 = txtFIRNo.getText();
            String value2 = txtVictimID.getText();
            String value3 = txtFName.getText();
            String value4 = txtSName.getText();
            String value5=txtLName.getText();
            
            String value6=txtAccusedId.getText();
            
            String dates=((JTextField)dtbFiled.getDateEditor().getUiComponent()).getText();
            String value8=txtTime.getText();
            //String value9=txtPlace.getText();
            
             String value9=cboLocation.getSelectedItem().toString();
             String value10=txtAIncedent.getText();
           
             
             
             String value11=cboCrimeType.getSelectedItem().toString();
             
             String searched=txtFirrecv.getText();
                
            String sql = "update  fir set FIR_No='" + value1 + "',Victim_ID='" + value2 + "',FName='" + value3 + "',SName='" + value4 + "',LName='" + value5 + "',Date_Filled='" + dates + "',time_filled='" + value8 + "',place_of_incident='" + value9 + "',incident='" + value10 + "',AccusedID='" + value6 + "',CrimeType='" + value11 + "' where FIR_No='" + searched + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
        
         }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void cmd_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmd_deleteActionPerformed

        
        if(txtFIRNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Type The OBR  you want to delete ");
        }
        else{
            
        
          int n=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete","CRPDAS",JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION)
        {
        
        String sql = "delete from   fir where FIR_No=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtFIRNo.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        }
        
        }
    }//GEN-LAST:event_cmd_deleteActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtFIRNo.setText("");
        txtFName.setText("");
        txtVictimID.setText("");
        txtLName.setText("");
        txtSName.setText("");
        txtAIncedent.setText("");
        //txtPlace.setText("");
        

    }//GEN-LAST:event_btnClearActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
        
            
        if(txtFIRNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter OBR Number","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtFIRNo.requestFocus();
            
        }
        else  if(txtVictimID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  victim ID","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtVictimID.requestFocus();
            
        }
        else  if(txtFName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter First Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtFName.requestFocus();
            
            
            
        }
         else  if(txtSName.getText().equals("")|| txtLName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Middle Name or Last  Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtSName.requestFocus();
           
        }
         
          else  if( txtAccusedId.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Select a Picture   Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtSName.requestFocus();
           
        }
         
        
          
            else  if(txtAIncedent.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  The Incident ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtAIncedent.requestFocus();
           
        }
            
              else  if(txtTime.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  The Time of  Incident ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtTime.requestFocus();
           
        }
            
           // else  if(((JTextField)dtbFiled.getDateEditor().getUiComponent().getText().isEmpty()) )
            
           /* else if(  try
                    {
                    
                       if( ((JTextField)dtbFiled.getDateEditor().getUiComponent().getText().isEmpty()))
                           
                       {
                                }}
                            catch(Exception ex)
                            {
                            }
                            )
                
        {
            JOptionPane.showMessageDialog(null,"Please Chooser a date ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtAIncedent.requestFocus();
           
        }*/
        
          
        else
         {
        try {
            String sql = "Insert  into fir(FIR_No,Victim_ID,FName,SName,LName,Date_Filled,time_filled,place_of_incident,incident,AccusedID,CrimeType)values(?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);

            pst.setString(1, txtFIRNo.getText());
            pst.setString(2, txtVictimID.getText());
            pst.setString(3, txtFName.getText());
            pst.setString(4, txtSName.getText());
            pst.setString(5, txtLName.getText());
            pst.setString(6, ((JTextField)dtbFiled.getDateEditor().getUiComponent()).getText());
            pst.setString(7, txtTime.getText());
             
             
             String value8=cboLocation.getSelectedItem().toString();//ComboBox 
                pst.setString(8, value8);
                
                
             pst.setString(9,txtAIncedent.getText());
              pst.setString(10,txtAccusedId.getText());
              
              
               String value2=cboCrimeType.getSelectedItem().toString();//ComboBox 
                pst.setString(11, value2);
           
            pst.execute();

            JOptionPane.showMessageDialog(null, "Saved Succesfully");

        }
        catch (SQLException er) {
            
            JOptionPane.showMessageDialog(null, "The Data is already Saved you cannot save it again","CRPDS Message",JOptionPane.INFORMATION_MESSAGE);
        }
        catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnSeacrhedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeacrhedActionPerformed
        // TODO add your handling code here:
         if(txtSearch.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter OBR Number  to search","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtSearch.requestFocus();
        }
        else 
        {
        
         try {
            String sql = "select * from  fir where FIR_No=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtSearch.getText());

            rs = pst.executeQuery();
            
            if (rs.next()) {
                String add1 = rs.getString("FIR_No");
                txtFIRNo.setText(add1);
                String add2 = rs.getString("Victim_ID");
                txtVictimID.setText(add2);
                String add3 = rs.getString("FName");
                txtFName.setText(add3);
                String add4 = rs.getString("SName");
                txtSName.setText(add4);
                String add5 = rs.getString("LName");
                txtLName.setText(add5);
                
                
                
                String dateValue = rs.getString("Date_Filled");
                java.util.Date add6 = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                dtbFiled.setDate(add6);
                
                String add7 = rs.getString("time_filled");
                txtTime.setText(add7);
                
                
                String addcon=rs.getString("place_of_incident");
                cboLocation.setSelectedItem(addcon);
                
                String add9 = rs.getString("incident");
                txtAIncedent.setText(add9);
                
                String add10 = rs.getString("AccusedID");
                txtAccusedId.setText(add10);
               
                
                
                String searched = rs.getString("FIR_No");
                txtFirrecv.setText(searched);

            }
            
             else
            {
                JOptionPane.showMessageDialog(null,"The Record has not been found","CRPDAS MEssage",JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         
        }
    }//GEN-LAST:event_btnSeacrhedActionPerformed

    private void txtVictimIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVictimIDKeyReleased
try {
            String sql = "select * from   victim where Victim_ID=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtVictimID.getText());

            rs = pst.executeQuery();
            
            if (rs.next()) {
                String add1 = rs.getString("FName");
                txtFName.setText(add1);
               
                String add3 = rs.getString("SName");
                txtSName.setText(add3);
                String add4 = rs.getString("LName");
                txtLName.setText(add4);
                
                 }

                } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                }        // TODO add your handling code here:
         
        
        
        
        
    }//GEN-LAST:event_txtVictimIDKeyReleased

    private void txtVictimIDKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVictimIDKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtVictimIDKeyPressed

    private void txtFIRNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFIRNoKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtFIRNo.getText().length()>30;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtFIRNoKeyTyped

    private void txtVictimIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtVictimIDKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtVictimID.getText().length()>15;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
        
        if(   (!(Character.isDigit(evt.getKeyChar()))) &&  (!(Character.isSpaceChar(evt.getKeyChar()))) && (evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)  &&(evt.getKeyChar()!=KeyEvent.VK_DELETE)&& (evt.getKeyChar()!=KeyEvent.VK_ESCAPE)  )
        {
            evt.consume();

            JOptionPane.showMessageDialog(null, "Numbers only","CRPDAS",JOptionPane.INFORMATION_MESSAGE);

        }

    }//GEN-LAST:event_txtVictimIDKeyTyped

    private void txtFNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNameKeyTyped
        // TODO add your handling code here:
        
         if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
        
         boolean max= txtFName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
         
    }//GEN-LAST:event_txtFNameKeyTyped

    private void txtSNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSNameKeyTyped
        // TODO add your handling code here:
        
         if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
                
                 boolean max= txtSName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
                
    }//GEN-LAST:event_txtSNameKeyTyped

    private void txtLNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyTyped

        
// TODO add your handling code here:
        
         if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
        
        boolean max= txtLName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtLNameKeyTyped

    private void txtAccusedIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAccusedIdKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtAccusedId.getText().length()>60;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        if(   (!(Character.isDigit(evt.getKeyChar()))) &&  (!(Character.isSpaceChar(evt.getKeyChar()))) && (evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)  &&(evt.getKeyChar()!=KeyEvent.VK_DELETE)&& (evt.getKeyChar()!=KeyEvent.VK_ESCAPE)  )
        {
            evt.consume();

            JOptionPane.showMessageDialog(null, "Numbers only","CRPDAS",JOptionPane.INFORMATION_MESSAGE);

        }

        
        
    }//GEN-LAST:event_txtAccusedIdKeyTyped

    private void dtbFiledKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dtbFiledKeyTyped
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_dtbFiledKeyTyped

    private void txtAIncedentKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAIncedentKeyTyped
        // TODO add your handling code here:
         if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
        boolean max= txtAIncedent.getText().length()>30;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
    }//GEN-LAST:event_txtAIncedentKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmFIR.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmFIR().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSeacrhed;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox cboCrimeType;
    private javax.swing.JComboBox cboLocation;
    private javax.swing.JButton cmd_delete;
    private com.toedter.calendar.JDateChooser dtbFiled;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea txtAIncedent;
    private javax.swing.JTextField txtAccusedId;
    private javax.swing.JTextField txtFIRNo;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtFirrecv;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSearched;
    private javax.swing.JTextField txtTime;
    private javax.swing.JTextField txtVictimID;
    // End of variables declaration//GEN-END:variables
}
