
//import com.sun.xml.internal.ws.api.config.management.policy.ManagementAssertion.Setting;
//import com.sun.xml.internal.ws.api.config.management.policy.ManagementAssertion.Setting;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.BufferedReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URISyntaxException;
import java.net.URL;
import java.net.URLConnection;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Se STRANGE W
 */
public class frmHome extends javax.swing.JFrame {

    /**
     * Creates new form frmHome
     */
    

    /**
     *
     */
    
    Connection conn = null;//name of intialized conn
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    public String[]getdatas=new String[1];
    
    public frmHome()
{
    
    
      initComponents();
    jPanel_Changer.setBackground(randomColor());
    event e =new event ();
    jPanel_Changer.addMouseListener(e);
    
    Clock();
    CurrentDate();
    User_res();
    
    txtUserType.setVisible(false);
}
public Color randomColor()
{
    int r=(int)(Math.random()*256);
    int g=(int)(Math.random()*256);
    int b=(int)(Math.random()*256);
    
    return(new Color(r,g,b) );
}

public void Clock()
{
    
    Thread clock=new Thread()
    {
        public void run()
        {
            try{
              for(;;)
              {
             Calendar cal=new GregorianCalendar();
             int sec=cal.get(Calendar.SECOND);
             int minute=cal.get(Calendar.MINUTE);
             int hour=cal.get(Calendar.HOUR);
    
    txt_Time.setText(hour+":"+(minute)+":"+sec);
                
            sleep(1000);
            }}
            catch(InterruptedException e )
            {
                e.printStackTrace();
            }
        }
    };
    clock.start();
   
}

public class event  implements MouseListener
{

        @Override
        public void mouseClicked(MouseEvent e) {
            jPanel_Changer.setBackground(randomColor());
        }

        @Override
        public void mousePressed(MouseEvent e) {
            
        }

        @Override
        public void mouseReleased(MouseEvent e) {
            
        }

        @Override
        public void mouseEntered(MouseEvent e) {
           
        }

        @Override
        public void mouseExited(MouseEvent e) {
           
        }
    
}
public void CurrentDate()
    {
        Calendar cal=new GregorianCalendar();
        int month=cal.get(Calendar.MONTH);
         int year=cal.get(Calendar.YEAR);
         int day=cal.get(Calendar.DAY_OF_MONTH);
         date_txt.setText(year+"/"+(month+1)+"/"+day);
         
         
         /*int second=cal.get(Calendar.SECOND);
         int minutes=cal.get(Calendar.MINUTE);
         int hour=cal.get(Calendar.HOUR);
         txt_Time.setText(hour+":"+(minutes)+":"+second);*/
    }

public void CurrentTime()
{
    
}


public void postData()
    {
        //String[] getdata = null;
        this.txtUserType.setText("txtUserlogin"+getdatas[0]);
    }
public void User_res()
{
    if(txtUserType.getText().equals("STANDARD"))
    {
        mnUsers.setEnabled(false);
    }
    else if(txtUserType.getText().equals("ADMIN1"))
    {
        
    }
    
    
//ADMIN2

}

 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem12 = new javax.swing.JMenuItem();
        pnlHome = new javax.swing.JPanel();
        date_txt = new javax.swing.JLabel();
        txt_Time = new javax.swing.JLabel();
        jPanel_Changer = new javax.swing.JPanel();
        lblWelcome = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblFooter = new javax.swing.JLabel();
        txtUserType = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnregisters = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jmiAccused = new javax.swing.JMenuItem();
        jmiVictim = new javax.swing.JMenuItem();
        jmiAccomplisher = new javax.swing.JMenuItem();
        jmiInvestigator = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnRJails = new javax.swing.JMenuItem();
        jmnInvestigation = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        mnReports = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        mnAccomplisher = new javax.swing.JMenuItem();
        mnOfficer = new javax.swing.JMenuItem();
        mnJails = new javax.swing.JMenuItem();
        mnObr = new javax.swing.JMenuItem();
        mnMissings = new javax.swing.JMenuItem();
        rptGProsecutor = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        mnrptCaseOutcome = new javax.swing.JMenuItem();
        mnVictim = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        mnSuspect = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jmi_totals_summary = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        mnUsers = new javax.swing.JMenu();
        JMIAdminstrator = new javax.swing.JMenuItem();
        JMIStaff = new javax.swing.JMenuItem();
        mnHelp1 = new javax.swing.JMenu();
        mnDispatchOfficers = new javax.swing.JMenuItem();
        mnDecision = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem13 = new javax.swing.JMenuItem();
        mnHelp = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        btnLogout = new javax.swing.JMenu();
        jMenuItem17 = new javax.swing.JMenuItem();

        jMenuItem12.setText("jMenuItem12");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CRIME RECORD PROCESSING AND DECISION ANALYSIS SYSTEM");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        pnlHome.setBackground(new java.awt.Color(255, 255, 255));

        date_txt.setBackground(new java.awt.Color(0, 51, 204));
        date_txt.setFont(new java.awt.Font("Telenor", 1, 18)); // NOI18N
        date_txt.setForeground(new java.awt.Color(0, 0, 204));
        date_txt.setText("Date");

        txt_Time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txt_Time.setForeground(new java.awt.Color(0, 0, 153));
        txt_Time.setText("TIME:");

        jPanel_Changer.setBackground(new java.awt.Color(204, 204, 255));
        jPanel_Changer.setForeground(new java.awt.Color(153, 153, 255));

        lblWelcome.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("WELCOME!!!");

        javax.swing.GroupLayout jPanel_ChangerLayout = new javax.swing.GroupLayout(jPanel_Changer);
        jPanel_Changer.setLayout(jPanel_ChangerLayout);
        jPanel_ChangerLayout.setHorizontalGroup(
            jPanel_ChangerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ChangerLayout.createSequentialGroup()
                .addGap(192, 192, 192)
                .addComponent(lblWelcome)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        jPanel_ChangerLayout.setVerticalGroup(
            jPanel_ChangerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ChangerLayout.createSequentialGroup()
                .addContainerGap(113, Short.MAX_VALUE)
                .addComponent(lblWelcome)
                .addGap(52, 52, 52))
        );

        jLabel4.setFont(new java.awt.Font("Onyx", 0, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Serving With Integrity ");

        lblFooter.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        lblFooter.setForeground(new java.awt.Color(0, 0, 102));
        lblFooter.setText("Smart&Little-Burney Productions, Copyright@ 2017. Email:smarbur@gmail.com");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 51, 153));
        jLabel2.setText("CRIME RECORD,PROCESSING AND DECISION ANALYSIS SYSTEM");

        jLabel3.setFont(new java.awt.Font("FrankRuehl", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 51, 204));
        jLabel3.setText("(CRPDAS)");

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Se STRANGE W\\Documents\\NetBeansProjects\\CRIME MANAGEMENT INFORMATION SYSTEM\\images\\crpds logo.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel3))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel3)
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlHomeLayout = new javax.swing.GroupLayout(pnlHome);
        pnlHome.setLayout(pnlHomeLayout);
        pnlHomeLayout.setHorizontalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel4)
                .addGap(167, 167, 167)
                .addComponent(jPanel_Changer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(txtUserType, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                .addContainerGap(190, Short.MAX_VALUE)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addComponent(lblFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(213, 213, 213))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133)
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txt_Time))
                        .addContainerGap())))
        );
        pnlHomeLayout.setVerticalGroup(
            pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(txtUserType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addComponent(date_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_Time)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(100, 100, 100)
                .addGroup(pnlHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHomeLayout.createSequentialGroup()
                        .addComponent(jPanel_Changer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlHomeLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(51, 51, 51)))
                .addComponent(lblFooter, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mnregisters.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        mnregisters.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Register.jpg"))); // NOI18N
        mnregisters.setText("Registers");
        mnregisters.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnregisters.add(jSeparator1);

        jmiAccused.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jmiAccused.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmiAccused.setText("Suspect Form");
        jmiAccused.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAccusedActionPerformed(evt);
            }
        });
        mnregisters.add(jmiAccused);

        jmiVictim.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jmiVictim.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmiVictim.setText("Victim Form");
        jmiVictim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiVictimActionPerformed(evt);
            }
        });
        mnregisters.add(jmiVictim);

        jmiAccomplisher.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jmiAccomplisher.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmiAccomplisher.setText("Accomplisher Form");
        jmiAccomplisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiAccomplisherActionPerformed(evt);
            }
        });
        mnregisters.add(jmiAccomplisher);

        jmiInvestigator.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        jmiInvestigator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmiInvestigator.setText("Officer's Form");
        jmiInvestigator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiInvestigatorActionPerformed(evt);
            }
        });
        mnregisters.add(jmiInvestigator);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem1.setText("Case Form");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnregisters.add(jMenuItem1);

        mnRJails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_MASK));
        mnRJails.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        mnRJails.setText("Jails");
        mnRJails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRJailsActionPerformed(evt);
            }
        });
        mnregisters.add(mnRJails);

        jmnInvestigation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.CTRL_MASK));
        jmnInvestigation.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jmnInvestigation.setText("Investigation Form");
        jmnInvestigation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmnInvestigationActionPerformed(evt);
            }
        });
        mnregisters.add(jmnInvestigation);

        jMenuItem3.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem3.setText("Prosecutor Form");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        mnregisters.add(jMenuItem3);

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem4.setText("FIR form");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        mnregisters.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem5.setText("Missings Form");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        mnregisters.add(jMenuItem5);

        jMenuItem6.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem6.setText("Locations");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        mnregisters.add(jMenuItem6);

        jMenuItem14.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem14.setText("Suspect_cam_Accomplisher");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        mnregisters.add(jMenuItem14);

        jMenuBar1.add(mnregisters);

        mnReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Report2.png"))); // NOI18N
        mnReports.setText("Reports");
        mnReports.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenu1.setText("General Reports");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        mnAccomplisher.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.SHIFT_MASK));
        mnAccomplisher.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnAccomplisher.setText("Accomplisher ");
        mnAccomplisher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnAccomplisherActionPerformed(evt);
            }
        });
        jMenu1.add(mnAccomplisher);

        mnOfficer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK));
        mnOfficer.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnOfficer.setText("Officers");
        mnOfficer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnOfficerActionPerformed(evt);
            }
        });
        jMenu1.add(mnOfficer);

        mnJails.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.SHIFT_MASK));
        mnJails.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnJails.setText("Jails");
        mnJails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnJailsActionPerformed(evt);
            }
        });
        jMenu1.add(mnJails);

        mnObr.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.SHIFT_MASK));
        mnObr.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnObr.setText("OBR");
        mnObr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnObrActionPerformed(evt);
            }
        });
        jMenu1.add(mnObr);

        mnMissings.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK));
        mnMissings.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnMissings.setText("Missings");
        mnMissings.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMissingsActionPerformed(evt);
            }
        });
        jMenu1.add(mnMissings);

        rptGProsecutor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        rptGProsecutor.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        rptGProsecutor.setText("Prosecutor");
        rptGProsecutor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rptGProsecutorActionPerformed(evt);
            }
        });
        jMenu1.add(rptGProsecutor);

        jMenuItem2.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem2.setText("Case");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        mnrptCaseOutcome.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.SHIFT_MASK));
        mnrptCaseOutcome.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnrptCaseOutcome.setText("Case Outcome");
        mnrptCaseOutcome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnrptCaseOutcomeActionPerformed(evt);
            }
        });
        jMenu1.add(mnrptCaseOutcome);

        mnVictim.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.SHIFT_MASK));
        mnVictim.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnVictim.setText("Victim");
        mnVictim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnVictimActionPerformed(evt);
            }
        });
        jMenu1.add(mnVictim);

        jMenuItem16.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem16.setText("Dispatch");
        jMenuItem16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem16ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem16);

        mnSuspect.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.SHIFT_MASK));
        mnSuspect.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnSuspect.setText("Suspect");
        mnSuspect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSuspectActionPerformed(evt);
            }
        });
        jMenu1.add(mnSuspect);

        mnReports.add(jMenu1);

        jMenu2.setText("Analyzed Reports");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jmi_totals_summary.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK));
        jmi_totals_summary.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jmi_totals_summary.setText("Totals_Summary");
        jmi_totals_summary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmi_totals_summaryActionPerformed(evt);
            }
        });
        jMenu2.add(jmi_totals_summary);

        jMenuItem7.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem7.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem7.setText("Gender Analysis ");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem9.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem9.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem9.setText("Investigations");
        jMenuItem9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem9ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem9);

        jMenuItem8.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem8.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem8.setText("Min and Max Crimes");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem11.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.SHIFT_MASK));
        jMenuItem11.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        jMenuItem11.setText("Decision Crime Charts Analyis");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        mnReports.add(jMenu2);

        jMenuBar1.add(mnReports);

        mnUsers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/AllUsers.png"))); // NOI18N
        mnUsers.setText("Users");
        mnUsers.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        JMIAdminstrator.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_1, java.awt.event.InputEvent.CTRL_MASK));
        JMIAdminstrator.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JMIAdminstrator.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Admin-icon.png"))); // NOI18N
        JMIAdminstrator.setText("Users Reports");
        JMIAdminstrator.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIAdminstratorActionPerformed(evt);
            }
        });
        mnUsers.add(JMIAdminstrator);

        JMIStaff.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_2, java.awt.event.InputEvent.CTRL_MASK));
        JMIStaff.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        JMIStaff.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Users Icon.png"))); // NOI18N
        JMIStaff.setText("Users Manager");
        JMIStaff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JMIStaffActionPerformed(evt);
            }
        });
        mnUsers.add(JMIStaff);

        jMenuBar1.add(mnUsers);

        mnHelp1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/HumanHelp.png"))); // NOI18N
        mnHelp1.setText("Dispatch");
        mnHelp1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnHelp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnHelp1ActionPerformed(evt);
            }
        });

        mnDispatchOfficers.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        mnDispatchOfficers.setText("Dispatch Officers");
        mnDispatchOfficers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDispatchOfficersActionPerformed(evt);
            }
        });
        mnHelp1.add(mnDispatchOfficers);

        jMenuBar1.add(mnHelp1);

        mnDecision.setText("Decision Expert System");
        mnDecision.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        mnDecision.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDecisionActionPerformed(evt);
            }
        });

        jMenuItem10.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem10.setText("Decision System");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        mnDecision.add(jMenuItem10);

        jMenuBar1.add(mnDecision);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/backup1.png"))); // NOI18N
        jMenu3.setText("Legacy Information");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem13.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem13.setText("Legacy Information");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuBar1.add(jMenu3);

        mnHelp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help-icon.png"))); // NOI18N
        mnHelp.setText("Help");
        mnHelp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        jMenuItem15.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_H, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jMenuItem15.setText("Help");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem15ActionPerformed(evt);
            }
        });
        mnHelp.add(jMenuItem15);

        jMenuBar1.add(mnHelp);

        btnLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/logout-icon.png"))); // NOI18N
        btnLogout.setText("Logout ");
        btnLogout.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        jMenuItem17.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.SHIFT_MASK | java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jMenuItem17.setText("Logout");
        jMenuItem17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem17ActionPerformed(evt);
            }
        });
        btnLogout.add(jMenuItem17);

        jMenuBar1.add(btnLogout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHome, javax.swing.GroupLayout.PREFERRED_SIZE, 525, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(1286, 677));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jmiAccusedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAccusedActionPerformed
        // TODO add your handling code here:
        //dispose();
        new  frmAccused().setVisible(true);  
        
        //new  frmAccused().setFocusableWindowState(true);  
       
                
       
        
    }//GEN-LAST:event_jmiAccusedActionPerformed

    private void jmiVictimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiVictimActionPerformed
        
        new  frmVictim().setVisible(true); 
    }//GEN-LAST:event_jmiVictimActionPerformed

    private void jmiAccomplisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiAccomplisherActionPerformed
       //        dispose();
        new  frmAccomplisher().setVisible(true); 
    }//GEN-LAST:event_jmiAccomplisherActionPerformed

    private void jmiInvestigatorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiInvestigatorActionPerformed
       // dispose();
        new  frmInvestigatorOfficer().setVisible(true); 
        
    }//GEN-LAST:event_jmiInvestigatorActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
      
       new frmLogin().setVisible(true);
        dispose();
        
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        
       // dispose();
        new  FrmCase().setVisible(true); 
        
        
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void JMIStaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIStaffActionPerformed
        // TODO add your handling code here:
        //new  frmStaff().setVisible(true);
        
        
         if(txtUserType.getText().equals("STANDARD"))
    {
        //mnUsers.setEnabled(false);
        new rptLogin_LogsReport().setVisible(false);
         
        JOptionPane.showMessageDialog(null,"Your Are not allowed to acccess This....Please Login As First/Second Administartor to Access This Reports","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
    }
     if(txtUserType.getText().equals("ADMIN1"))
    {
         new frmStaff().setVisible(true);
         
    }
        
     else if(txtUserType.getText().equals("ADMIN2"))
    {
         new frmStaff().setVisible(true);
         
    }
    }//GEN-LAST:event_JMIStaffActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        
        new Prosecutor().setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        
        new frmFIR().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        // TODO add your handling code here:
        new frmMissings().setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void mnMissingsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMissingsActionPerformed
        // TODO add your handling code here:
        
        new rptMissings().setVisible(true);
    }//GEN-LAST:event_mnMissingsActionPerformed

    private void mnSuspectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSuspectActionPerformed
        // TODO add your handling code here:
       new  rptSuspects().setVisible(true);
    }//GEN-LAST:event_mnSuspectActionPerformed

    private void mnRJailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRJailsActionPerformed
        // TODO add your handling code here:
        
        new frmJails().setVisible(true);
    }//GEN-LAST:event_mnRJailsActionPerformed

    private void rptGProsecutorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rptGProsecutorActionPerformed
        // TODO add your handling code here:
        
        new rptProsecutor().setVisible(true);
        
    }//GEN-LAST:event_rptGProsecutorActionPerformed

    private void mnrptCaseOutcomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnrptCaseOutcomeActionPerformed
        // TODO add your handling code here:
        
         new RptCase_Outcome().setVisible(true);
    }//GEN-LAST:event_mnrptCaseOutcomeActionPerformed

    private void mnObrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnObrActionPerformed
        // TODO add your handling code here:
        new rptObr().setVisible(true);
        
        
    }//GEN-LAST:event_mnObrActionPerformed

    private void mnHelp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnHelp1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnHelp1ActionPerformed

    private void mnDispatchOfficersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDispatchOfficersActionPerformed
        // TODO add your handling code here:
        new frmDispatch().setVisible(true);
    }//GEN-LAST:event_mnDispatchOfficersActionPerformed

    private void jmi_totals_summaryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmi_totals_summaryActionPerformed
        // TODO add your handling code here:
        
        new rpt_Anlyz_Totals().setVisible(true);
    }//GEN-LAST:event_jmi_totals_summaryActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        // TODO add your handling code here:
        
        new frmLocation().setVisible(true);
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        // TODO add your handling code here:
        new rptGenderAnalyis().setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        new rptMax_minCrime().setVisible(true);
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem9ActionPerformed
        // TODO add your handling code here:
        
        new rptInvestigations().setVisible(true);
    }//GEN-LAST:event_jMenuItem9ActionPerformed

    private void mnDecisionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDecisionActionPerformed
        // TODO add your handling code here:
        
        new frmDecision().setVisible(true);
    }//GEN-LAST:event_mnDecisionActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        // TODO add your handling code here:
        new frmDecision().setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
        // TODO add your handling code here:
        
         new frmLegacy_infomation().setVisible(true);
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        // TODO add your handling code here:
        
        new frmCharts().setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem15ActionPerformed
        // TODO add your handling code here:
        
       if(Desktop.isDesktopSupported())
{
           try {
               Desktop.getDesktop().browse(new URI("http://localhost/Help_crpds/"));
           } catch (IOException ex) {
               Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
           } catch (URISyntaxException ex) {
               Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
           }
}
        
        
        
        
        
        
        
        /* URL oracle;
        try {
            oracle = new URL("http://www.oracle.com/");
            URLConnection yc = oracle.openConnection();
        BufferedReader in = new BufferedReader(new InputStreamReader(
                                    yc.getInputStream()));
        
        String inputLine;
        while ((inputLine = in.readLine()) != null) 
            System.out.println(inputLine);
        in.close();
        } catch (MalformedURLException ex) {
            Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
        }*/
        
        
        /*try {

     String url ="http://localhost/Help_crpds/";

     Desktop dt = Desktop.getDesktop();
     URI uri = new URI(url);
     dt.browse(uri.resolve(uri));


 } catch (URISyntaxException ex) {
     Logger.getLogger(Setting.class.getName()).log(Level.SEVERE, null, ex);
 } catch (IOException ex) {
     Logger.getLogger(Setting.class.getName()).log(Level.SEVERE, null, ex);
 }
        
                */
                
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem16ActionPerformed
        // TODO add your handling code here:
        new rptDispatch().setVisible(true);
    }//GEN-LAST:event_jMenuItem16ActionPerformed

    private void mnAccomplisherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnAccomplisherActionPerformed
        // TODO add your handling code here:
        
         new rptAccomplisher().setVisible(true);
    }//GEN-LAST:event_mnAccomplisherActionPerformed

    private void mnOfficerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnOfficerActionPerformed
        // TODO add your handling code here:
        
                
                new rptOfficers().setVisible(true);
    }//GEN-LAST:event_mnOfficerActionPerformed

    private void mnJailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnJailsActionPerformed
        // TODO add your handling code here:
        new frmSrchJails().setVisible(true);
    }//GEN-LAST:event_mnJailsActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        new rptCase().setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void mnVictimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnVictimActionPerformed
                    // TODO add your handling code here:
        new frmSrchVictim().setVisible(true);
        
    }//GEN-LAST:event_mnVictimActionPerformed

    private void JMIAdminstratorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JMIAdminstratorActionPerformed
        // TODO add your handling code here:
        
        if(txtUserType.getText().equals("STANDARD"))
    {
        //mnUsers.setEnabled(false);
        new rptLogin_LogsReport().setVisible(false);
         
        JOptionPane.showMessageDialog(null,"Your Are not allowed to acccess This....Please Login As First/Second Administartor to Access This Reports","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
    }
     if(txtUserType.getText().equals("ADMIN1"))
    {
         new rptLogin_LogsReport().setVisible(true);
         
    }
        
     else if(txtUserType.getText().equals("ADMIN2"))
    {
         new rptLogin_LogsReport().setVisible(true);
         
    }
        
    }//GEN-LAST:event_JMIAdminstratorActionPerformed

    private void jmnInvestigationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmnInvestigationActionPerformed
        // TODO add your handling code here:
        
         //new testingdsd().setVisible(true);
       new frmInvestigationTable().setVisible(true);
        
       
        
    }//GEN-LAST:event_jmnInvestigationActionPerformed

    private void jMenuItem17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem17ActionPerformed
        
        
        
        
        
    
        
        new frmLogin().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem17ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
        // TODO add your handling code here:
        
        
        new frmAccom_cam_Suspect().setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
               // UIManager.setLookAndFeel("com.jtattoo.plaf.aero.AeroLookAndFeel");
               // UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
                //UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
                
                UIManager.setLookAndFeel("com.jtattoo.plaf.acryl.AcrylLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmHome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmHome().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JMenuItem JMIAdminstrator;
    public javax.swing.JMenuItem JMIStaff;
    public javax.swing.JMenu btnLogout;
    private javax.swing.JLabel date_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    public javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem2;
    public javax.swing.JMenuItem jMenuItem3;
    public javax.swing.JMenuItem jMenuItem4;
    public javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel_Changer;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    public javax.swing.JMenuItem jmiAccomplisher;
    public javax.swing.JMenuItem jmiAccused;
    public javax.swing.JMenuItem jmiInvestigator;
    public javax.swing.JMenuItem jmiVictim;
    private javax.swing.JMenuItem jmi_totals_summary;
    public javax.swing.JMenuItem jmnInvestigation;
    private javax.swing.JLabel lblFooter;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JMenuItem mnAccomplisher;
    private javax.swing.JMenu mnDecision;
    private javax.swing.JMenuItem mnDispatchOfficers;
    public javax.swing.JMenu mnHelp;
    public javax.swing.JMenu mnHelp1;
    private javax.swing.JMenuItem mnJails;
    private javax.swing.JMenuItem mnMissings;
    private javax.swing.JMenuItem mnObr;
    private javax.swing.JMenuItem mnOfficer;
    public javax.swing.JMenuItem mnRJails;
    public javax.swing.JMenu mnReports;
    private javax.swing.JMenuItem mnSuspect;
    public javax.swing.JMenu mnUsers;
    private javax.swing.JMenuItem mnVictim;
    public javax.swing.JMenu mnregisters;
    private javax.swing.JMenuItem mnrptCaseOutcome;
    private javax.swing.JPanel pnlHome;
    private javax.swing.JMenuItem rptGProsecutor;
    public static javax.swing.JTextField txtUserType;
    private javax.swing.JLabel txt_Time;
    // End of variables declaration//GEN-END:variables
}
