
import bsh.ParserConstants;
import com.toedter.calendar.JDateChooser;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.io.ByteArrayOutputStream;
import java.io.File;
import java.io.FileInputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ButtonGroup;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Se STRANGE W
 */
public class frmInvestigatorOfficer extends javax.swing.JFrame {
 private String Gender;
 Connection conn = null;//name of intialized conn
    PreparedStatement pst = null;
    ResultSet rs = null;
    
    
private ImageIcon format=null;// for image load 
String filename=null;//for attaching images 
int s=0;
byte[]person_image=null;
    /**
     * Creates new form frmInvestigatorOfficer
     */
    public frmInvestigatorOfficer() {
        initComponents();
        conn = DatabaseConnection.ConnecrDb();
        GenderSelect = new ButtonGroup();
        GenderSelect.add(Male);
        GenderSelect.add(Female);
        Fill_location();
        
       // new  frmInvestigatorOfficer().setAlwaysOnTop(true);
        
        txtpath.setVisible(false);
        jDateChooser_DOB.getJCalendar().setMaxSelectableDate(new Date());
        jDateChooser_DOH.getJCalendar().setMaxSelectableDate(new Date());
    }
    EmailValidator emailValidator = new EmailValidator();
    EphoneValidator ephone= new EphoneValidator();
    
    
     private void Fill_location()
    {
        try {
            
            String sql="select * from locations";
            pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next())
            {
                String location=rs.getString("LocationName");
                cboLocations.addItem(location);
                
                        
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GenderSelect = new javax.swing.ButtonGroup();
        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btnDelete = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblCOntactNo1 = new javax.swing.JLabel();
        txtIDNo = new javax.swing.JTextField();
        lblFName1 = new javax.swing.JLabel();
        txtContactNo = new javax.swing.JTextField();
        lblIOID1 = new javax.swing.JLabel();
        txtIOID = new javax.swing.JTextField();
        txtDesignation = new javax.swing.JTextField();
        lblFName = new javax.swing.JLabel();
        txtLName = new javax.swing.JTextField();
        lblEmail = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblCOntactNo = new javax.swing.JLabel();
        lblGender1 = new javax.swing.JLabel();
        txtFName = new javax.swing.JTextField();
        lblEmail1 = new javax.swing.JLabel();
        lblSName = new javax.swing.JLabel();
        lblIOID = new javax.swing.JLabel();
        cboRank = new javax.swing.JComboBox();
        txtSName = new javax.swing.JTextField();
        lblSName1 = new javax.swing.JLabel();
        lblLName = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblLName1 = new javax.swing.JLabel();
        Female = new javax.swing.JRadioButton();
        Male = new javax.swing.JRadioButton();
        jDateChooser_DOB = new com.toedter.calendar.JDateChooser();
        jDateChooser_DOH = new com.toedter.calendar.JDateChooser();
        txtpath = new javax.swing.JTextField();
        btnAttach = new javax.swing.JButton();
        txtShift = new javax.swing.JComboBox();
        cboLocations = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        photo = new javax.swing.JLabel();
        btnViewPhoto = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtSearch1 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        txt_search = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblTopName = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        btnTableSearch = new javax.swing.JButton();
        cboCriteria = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        txtCriterion = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("POLICE OFFICERS REGISTER");
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        jPanel2.setBackground(new java.awt.Color(150, 158, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12), new java.awt.Color(0, 0, 153))); // NOI18N

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon("C:\\CrpdasSystem\\images\\icons\\delete1.jpg")); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_icon.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        btnClear.setText("CLEAR");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-file-icon.png"))); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnSave)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnUpdate)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClear)
                .addGap(10, 10, 10)
                .addComponent(btnDelete))
        );

        jPanel1.setBackground(new java.awt.Color(150, 158, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Police Officer's Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        lblCOntactNo1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCOntactNo1.setText("PHOTO:");

        txtIDNo.setNextFocusableComponent(txtIOID);
        txtIDNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIDNoKeyTyped(evt);
            }
        });

        lblFName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFName1.setText("SHIFT:");

        txtContactNo.setToolTipText("The Contact Number should Begin with+2547...xxxxxxxxxx");
        txtContactNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtContactNoKeyTyped(evt);
            }
        });

        lblIOID1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIOID1.setText("RANK:");

        txtIOID.setNextFocusableComponent(txtFName);
        txtIOID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIOIDKeyTyped(evt);
            }
        });

        txtDesignation.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDesignationKeyTyped(evt);
            }
        });

        lblFName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblFName.setText("FIRST NAME:");

        txtLName.setNextFocusableComponent(Male);
        txtLName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtLNameKeyTyped(evt);
            }
        });

        lblEmail.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail.setText("EMAIL:");

        lblGender.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGender.setText("GENDER:");

        lblCOntactNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCOntactNo.setText("CONTACT NO:");

        lblGender1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblGender1.setText("DESIGNATION:");

        txtFName.setNextFocusableComponent(txtSName);
        txtFName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtFNameKeyTyped(evt);
            }
        });

        lblEmail1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEmail1.setText("IDENTIFICATION NO:");

        lblSName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSName.setText("SECOND NAME:");

        lblIOID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblIOID.setText("INVESTIGATOR ID:");

        cboRank.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Lieutenant I", "Lieutenant I", "Commissioner of Police", "Senior Deputy Commissioner of Police I", "Senior Deputy Commissioner of Police II", "Deputy Commissioner of Police", "Senior Assistant Commissioner of Police", "Assistant Commissioner of Police", "Senior Superintendent of Police", "Superintendent of Police", "Acting Superintendent of Police", "Chief Inspector", "Inspector", "Acting Inspector", "Senior Sergeant", "Sergeant", "Corporal", "Police Constable" }));

        txtSName.setNextFocusableComponent(txtLName);
        txtSName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSNameKeyTyped(evt);
            }
        });

        lblSName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSName1.setText("DATE OF HIRE:");

        lblLName.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLName.setText("LAST NAME");

        txtEmail.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                txtEmailInputMethodTextChanged(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtEmailKeyTyped(evt);
            }
        });

        lblLName1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblLName1.setText("DATE OF BIRTH:");

        Female.setText("FEMALE");
        Female.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FemaleActionPerformed(evt);
            }
        });

        Male.setText("MALE");
        Male.setNextFocusableComponent(txtContactNo);
        Male.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaleActionPerformed(evt);
            }
        });

        jDateChooser_DOB.setDateFormatString("yyyy-MM-dd");

        jDateChooser_DOH.setDateFormatString("yyyy-MM-dd");

        btnAttach.setText("Attach Photo");
        btnAttach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAttachActionPerformed(evt);
            }
        });

        txtShift.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "All", "Day", "Night" }));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Location");

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(photo)
                .addGap(76, 76, 76))
        );
        jDesktopPane1.setLayer(photo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        btnViewPhoto.setText("View Photo");
        btnViewPhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewPhotoActionPerformed(evt);
            }
        });

        jLabel4.setText("Start the phone number with +2547");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblCOntactNo)
                            .addComponent(lblGender, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Male)
                                .addGap(18, 18, 18)
                                .addComponent(Female)
                                .addGap(37, 37, 37))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 9, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblCOntactNo1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblEmail, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cboLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(btnAttach)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(2, 2, 2)
                                        .addComponent(jLabel4))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblFName)
                                .addGap(64, 64, 64)
                                .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(5, 5, 5))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblLName)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(lblIOID, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblEmail1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtIDNo, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtIOID, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblIOID1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblLName1))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(lblFName1)
                                        .addGap(25, 25, 25)))
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(lblSName1)
                                .addGap(18, 18, 18)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser_DOH, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                            .addComponent(txtShift, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblGender1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(1, 1, 1)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDesignation)
                            .addComponent(cboRank, 0, 1, Short.MAX_VALUE)
                            .addComponent(jDateChooser_DOB, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(108, 108, 108)
                        .addComponent(jDesktopPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(btnViewPhoto)
                .addGap(147, 147, 147)
                .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIOID1)
                            .addComponent(cboRank, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jDateChooser_DOH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(16, 16, 16)
                        .addComponent(jDateChooser_DOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFName1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtShift, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDesignation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblGender1)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblEmail1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtIDNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIOID)
                            .addComponent(txtIOID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtFName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblSName1))
                        .addGap(9, 9, 9)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSName)
                            .addComponent(txtSName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLName1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblLName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtLName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblGender)
                            .addComponent(Male)
                            .addComponent(Female))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtContactNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCOntactNo, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDesktopPane1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblCOntactNo1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnAttach)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cboLocations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnViewPhoto)
                    .addComponent(txtpath, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        jPanel3.setBackground(new java.awt.Color(150, 158, 153));

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Please Use Police Id No to search");

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search-icon.png"))); // NOI18N
        jButton1.setText("Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(43, 43, 43))
        );

        lblTopName.setBackground(new java.awt.Color(204, 204, 204));
        lblTopName.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblTopName.setForeground(new java.awt.Color(255, 255, 255));
        lblTopName.setText("Police Officers Register ");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Please Fill the details Correctly");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(227, 227, 227)
                        .addComponent(lblTopName, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTopName, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(114, 114, 114)
                        .addComponent(txtSearch1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Register Form", jPanel4);

        jPanel7.setBackground(new java.awt.Color(102, 102, 255));

        btnTableSearch.setText("Search");
        btnTableSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTableSearchActionPerformed(evt);
            }
        });

        cboCriteria.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Gender", "Rank", "Designation", "Shift", "Location", " " }));

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSearchMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblSearch);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(cboCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCriterion, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnTableSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cboCriteria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCriterion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTableSearch))
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(301, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Advance Search", jPanel5);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(929, 640));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void FemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FemaleActionPerformed

        Gender="Female";
    }//GEN-LAST:event_FemaleActionPerformed

    private void MaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaleActionPerformed
        Gender="Male";
    }//GEN-LAST:event_MaleActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       
          if(txtIDNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  National Identification Number","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtIDNo.requestFocus();
            
        }
        else  if(txtIOID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Investigator ID ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtIOID.requestFocus();
            
            
            
        }
         else  if(txtFName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  First Name  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtFName.requestFocus();
           
        }
         
          else  if( txtSName.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Second Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtSName.requestFocus();
           
        }
          
          else  if( txtLName.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Last  Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtLName.requestFocus();
           
        }
          
          else  if( txtContactNo.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Contact  Number ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtContactNo.requestFocus();
           
        }
           else if(!ephone.validate(txtContactNo.getText().trim()))
        {
            
             JOptionPane.showMessageDialog(null,"The Phone Number is Invalid  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtContactNo.requestFocus();
        }
       
          
          else  if( txtEmail.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Email Address ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtEmail.requestFocus();
           
        }
          
        else if(!emailValidator.validate(txtEmail.getText().trim()))
        {
            
             JOptionPane.showMessageDialog(null,"The Email Address is Invalid  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtEmail.requestFocus();
        }
       
        else  if( txtpath.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please  Select a  Photo for Officer ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtpath.requestFocus();
           
        }
          
          else  if( jDateChooser_DOH.getDate()==null  )
        {
            JOptionPane.showMessageDialog(null,"Please Select Date of Hire  ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            jDateChooser_DOH.requestFocus();
           
        }
         
        else  if( jDateChooser_DOB.getDate()==null  )
        {
            JOptionPane.showMessageDialog(null,"Please Select Date of Birth  ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
            jDateChooser_DOB.requestFocus();
           
        }  
        
        else if(GenderSelect.getSelection()==null)
        {
            JOptionPane.showMessageDialog(null,"Please Select the Gender of the Person ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            Male.requestFocus();
           
        }
        
        else 
        {
         try {
            String sql = "Insert  into  investigation_officer(IO_ID,ID_No,fName,mName,Lname,Gender,ContactNo,Email,rank,shift,Date_of_Hire,DOB,Des_Area,photo)values(?,?,?,?,?,?,?,?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            
            //PreparedStatement.RETURN_GENERATED_KEYS

            pst.setString(1, txtIDNo.getText());
            pst.setString(2, txtIOID.getText());
            pst.setString(3, txtFName.getText());
            pst.setString(4, txtSName.getText());
            pst.setString(5, txtLName.getText());
            pst.setString(6, Gender);
            pst.setString(7, txtContactNo.getText());
            pst.setString(8, txtEmail.getText());
                
             String value=cboRank.getSelectedItem().toString();//ComboBox 
            pst.setString(9, value);
            
            
            String value2=txtShift.getSelectedItem().toString();
             pst.setString(10, value2);
             
            pst.setString(11, ((JTextField)jDateChooser_DOH.getDateEditor().getUiComponent()).getText());
            pst.setString(12, ((JTextField)jDateChooser_DOB.getDateEditor().getUiComponent()).getText());
            pst.setString(13, txtDesignation.getText());
            
            pst.setString(14, txtpath.getText());
           // pst.setBytes(14,person_image);//takes the image from the viarable declared in the form
            pst.execute();
            
            JOptionPane.showMessageDialog(null, "Saved Succesfully");
         }
         
         catch (SQLException er) {
            
           JOptionPane.showMessageDialog(null, "The Data is already Saved you cannot save it again....if problem Persist contact Administrator","CRPDS Message",JOptionPane.INFORMATION_MESSAGE);
        }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
         
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnAttachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAttachActionPerformed
         JFileChooser chooser=new JFileChooser();
       chooser.showOpenDialog(null);
       File f= chooser.getSelectedFile();
       
       filename=f.getAbsolutePath();// declared at bottom to make the string filename global variable 
       txtpath.setText(filename);
       
       Icon icon = new ImageIcon(filename);
            
            photo.setIcon(icon);
       
       try
       { 
           //This convert the image into byte which is later saved into the variable person_image 
           File image = new File(filename);
           FileInputStream fis= new FileInputStream(image);
           
           ByteArrayOutputStream bos=new ByteArrayOutputStream();
           byte[] buf= new byte [1024];
           
           for(int readNum;(readNum=fis.read(buf))!=-1;)
           {
               bos.write(buf,0,readNum);
           }
           
            person_image=bos.toByteArray();//variable for saving image into 
       }
       catch(Exception e)
       {
           JOptionPane.showMessageDialog(null, e);
       }
    }//GEN-LAST:event_btnAttachActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased
        
        
         
    }//GEN-LAST:event_txt_searchKeyReleased

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        
        txtIDNo.setText("");
        txtIOID.setText("");
        txtFName.setText("");
        txtSName.setText("");
        txtLName.setText("");
        txtContactNo.setText("");
        txtEmail.setText("");
        cboRank.addItem("");
        
        txtDesignation.setText("");
        txtpath.setText("");
        Male.setSelected(false);
        Female.setSelected(false);
        JDateChooser dateChooser = new JDateChooser();
        dateChooser.setCalendar(null);
       // jDateChooser_DOH.setText("");
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        if(txtIOID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Type The Officer Id you want to delete ");
        }
        else{
        
        
        int n=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete","CRPDAS",JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION)
        {
        
          String sql = "delete from victim where IO_ID =?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtIOID.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }}
        
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
         if(txtIDNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  National Identification Number","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtIDNo.requestFocus();
            
        }
        else  if(txtIOID.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Investigator ID ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtIOID.requestFocus();
            
            
            
        }
         else  if(txtFName.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  First Name  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtFName.requestFocus();
           
        }
         
          else  if( txtSName.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Second Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtSName.requestFocus();
           
        }
          
          else  if( txtLName.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Last  Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtLName.requestFocus();
           
        }
          
          else  if( txtContactNo.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Contact  Number ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtContactNo.requestFocus();
           
        }
          
          else if(!ephone.validate(txtContactNo.getText().trim()))
        {
            
             JOptionPane.showMessageDialog(null,"The Phone Number is Invalid  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtEmail.requestFocus();
        }
          else  if( txtEmail.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Email Address ","CRPDASMessage",JOptionPane.INFORMATION_MESSAGE);
            txtEmail.requestFocus();
           
        }
          
        else if(!emailValidator.validate(txtEmail.getText().trim()))
        {
            
             JOptionPane.showMessageDialog(null,"The Email Address is Invalid  ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtEmail.requestFocus();
        }
       
        else  if( txtpath.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please  Select a  Photo for Officer ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtpath.requestFocus();
           
        }
          
          else  if( jDateChooser_DOH.getDate()==null  )
        {
            JOptionPane.showMessageDialog(null,"Please Select Date of Hire  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            jDateChooser_DOH.requestFocus();
           
        }
         
        else  if( jDateChooser_DOB.getDate()==null  )
        {
            JOptionPane.showMessageDialog(null,"Please Select Date of Birth  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            jDateChooser_DOB.requestFocus();
           
        }  
        
        else if(GenderSelect.getSelection()==null)
        {
            JOptionPane.showMessageDialog(null,"Please Select the Gender of the Person ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            Male.requestFocus();
           
        }
        
        else 
        {
        
         try {

            String value1 = txtIDNo.getText();
            String value2 = txtIOID.getText();
            String value3 = txtFName.getText();
            String value4 = txtSName.getText();
            String value5 = txtLName.getText();
            String value6=Gender;
            
                    
            String value7 = txtContactNo.getText();
            String value8 = txtEmail.getText();
            String value9=cboRank.getSelectedItem().toString();
            //dates included 2
            String value10=((JTextField)jDateChooser_DOH.getDateEditor().getUiComponent()).getText();
            String value11=((JTextField)jDateChooser_DOB.getDateEditor().getUiComponent()).getText();
            
            
            String value12=txtShift.getSelectedItem().toString();
            
            
            String value13 = txtDesignation.getText();
            
            
            //photo
            
            String value14=txtpath.getText();
            
             String searchn = txtSearch1.getText();
             
             
             
            

            String sql = "update investigation_officer set IO_ID='" + value2 + "',ID_No='" + value1 + "',fName='" + value3 + "',"
                    + "mName='" + value4 + "',Lname='" + value5 + "',Gender='" + value6 + "',"
                    + "ContactNo='" + value7 + "',Email='" + value8 + "',rank='" + value9 + "',shift='" + value12 + "',"
                    + "Date_of_Hire='" + value10 + "',DOB='" + value11 + "',Des_Area='" + value13 + "',photo='" + value14 + "' where IO_ID='" + searchn + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
         
        }
        
        
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        
// TODO add your handling code here:
        
        if(txt_search.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Investigatator Number   to search","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txt_search.requestFocus();
        }
        else 
        {  
        
         try {
            String sql = "select * from    investigation_officer where IO_ID =?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText());

            rs = pst.executeQuery();
            if (rs.next()) {
                String add1=rs.getString("IO_ID");
                txtIOID.setText(add1);
                String add2 = rs.getString("ID_No");
                txtIDNo.setText(add2);
                String add3 = rs.getString("fName");
                txtFName.setText(add3);
                String add4 = rs.getString("mName");
                txtSName.setText(add4);
                String add5 = rs.getString("Lname");
                txtLName.setText(add5);
                
                 String add6 = rs.getString("Gender");
                 if (add6.equals("Female")){
                  Male.setSelected(false);
                 Female.setSelected(true);
                 } else {
                 Female.setSelected(false);
                 Male.setSelected(true);
                }
               
                 String add7 = rs.getString("ContactNo");
                txtContactNo.setText(add7);
                String add8=rs.getString("Email");
                 txtEmail.setText(add8);
                 
                 String pat = rs.getString("Rank");
                   cboRank.addItem(pat);
                   
                   
                   String pated = rs.getString("shift");
                   txtShift.addItem(pated);
                   
                 String dateValue = rs.getString("Date_of_Hire"); // What ever column
                java.util.Date add11 = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                jDateChooser_DOH.setDate(add11);
                
                 String dateValue2 = rs.getString("DOB"); // What ever column
                java.util.Date add12 = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue2);
                jDateChooser_DOB.setDate(add12);
                
                String add13=rs.getString("Des_Area");
                   txtDesignation.setText(add13);           
              
                   
                   String add15=rs.getString("IO_ID");
                   txtSearch1.setText(add15);
                   
                   
                   
                  //  byte[]imagedata=rs.getBytes("photo");
               // ImageIcon imageicon= new ImageIcon(new ImageIcon(imagedata).getImage().getScaledInstance(photo.getWidth(),photo.getHeight(),Image.SCALE_DEFAULT));
               // format=new ImageIcon(imagedata);
               // photo.setIcon(imageicon);
                
                String add14=rs.getString("photo");
                //photo.setIcon(add14);
                
                
                
                //File f= chooser.getSelectedFile();
       
       //add14=f.getAbsolutePath();// declared at bottom to make the string filename global variable 
       txtpath.setText(add14);
       filename=txtpath.getText();
       
       Icon icon = new ImageIcon(filename);
            
            photo.setIcon(icon);

            }
            
             else
            {
                JOptionPane.showMessageDialog(null,"The Record has not been found","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            }


        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
          
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void txtIDNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIDNoKeyTyped
        // TODO add your handling code here:
        
         if(   (!(Character.isDigit(evt.getKeyChar()))) &&  (!(Character.isSpaceChar(evt.getKeyChar()))) && (evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)  &&(evt.getKeyChar()!=KeyEvent.VK_DELETE)&& (evt.getKeyChar()!=KeyEvent.VK_ESCAPE)  )
        {
            evt.consume();
            
           JOptionPane.showMessageDialog(null, "Numbers only  i.e 0-9","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            
            
        
        }
         
         boolean max= txtIDNo.getText().length()>15;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtIDNoKeyTyped

    private void txtIOIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIOIDKeyTyped
        // TODO add your handling code here:
        
         if(   (!(Character.isDigit(evt.getKeyChar()))) &&  (!(Character.isSpaceChar(evt.getKeyChar()))) && (evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)  &&(evt.getKeyChar()!=KeyEvent.VK_DELETE)&& (evt.getKeyChar()!=KeyEvent.VK_ESCAPE)  )
        {
            evt.consume();
            
           JOptionPane.showMessageDialog(null, "Numbers only  i.e 0-9","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            
            
        
        }
        
        boolean max= txtIOID.getText().length()>15;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtIOIDKeyTyped

    private void txtFNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFNameKeyTyped
        // TODO add your handling code here:
        boolean max= txtFName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
        }
        
         if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
        
    }//GEN-LAST:event_txtFNameKeyTyped

    private void txtSNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSNameKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtSName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
         if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
    }//GEN-LAST:event_txtSNameKeyTyped

    private void txtLNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLNameKeyTyped
        // TODO add your handling code here:
        boolean max= txtLName.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
        
         if(!(Character.isLetter(evt.getKeyChar())))
        {
            evt.consume();
           
        }
       
    }//GEN-LAST:event_txtLNameKeyTyped

    private void txtContactNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactNoKeyTyped
        // TODO add your handling code here:
        
        
        boolean max= txtContactNo.getText().length()>12;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of characters reached..Contact Number does not pass that  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        
    }//GEN-LAST:event_txtContactNoKeyTyped

    private void txtEmailKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyTyped
        // TODO add your handling code here:
        
        
       
         boolean max= txtContactNo.getText().length()>40;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtEmailKeyTyped

    private void txtDesignationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDesignationKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtDesignation.getText().length()>20;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtDesignationKeyTyped

    private void txtEmailInputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_txtEmailInputMethodTextChanged
        // TODO add your handling code here:
        
         
        
    }//GEN-LAST:event_txtEmailInputMethodTextChanged

    private void btnTableSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTableSearchActionPerformed
        // TODO add your handling code here:
        
        if(cboCriteria.getSelectedItem().equals("Gender"))
        {
            
        
        
         try{
            
             String sql="select * from   investigation_officer  where Gender='"+txtCriterion.getText()+"'";
            
             
     
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        tblSearch.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch( Exception e )
                {
                    JOptionPane.showMessageDialog(null, e);
                   // JOptionPane.showMessageDialog(null,"Table problem");
                }
        
        }
        else if(cboCriteria.getSelectedItem().equals(""))
        {
            try{
            
             String sql="select * from   investigation_officer  where Gender='Male'";
            
             
     
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
        tblSearch.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch( Exception e )
                {
                    JOptionPane.showMessageDialog(null, e);
                   // JOptionPane.showMessageDialog(null,"Table problem");
                }
        }
        
         else if(cboCriteria.getSelectedItem().equals(""))
        {
            
        }
        
         else if(cboCriteria.getSelectedItem().equals(""))
        {
            
        }
        
    }//GEN-LAST:event_btnTableSearchActionPerformed

    private void tblSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSearchMouseClicked
        // TODO add your handling code here:
        
        
        DefaultTableModel dtm = (DefaultTableModel) tblSearch.getModel(); //create a model
    int selectedRowIndex = tblSearch.getSelectedRow(); //get selected row
    Integer id = (Integer) dtm.getValueAt(selectedRowIndex, 0); //get the primary key to fetch data.
    try {
        
        String sql="Select * from  investigation_officer where IO_ID= '"+id+"'";
        pst=conn.prepareStatement(sql);
        rs=pst.executeQuery();
         //rs = pst.getData("Select * from legacy_info where legacy_no= '"+id+"'"); //dont worry about dbcon.getdata, its my class to get data.
        while(rs.next()){    //u can use normal query
            txtIDNo.setText(rs.getString("IO_ID"));  //these are my textfields
            txtIOID.setText(rs.getString("ID_No"));
            txtFName.setText(rs.getString("fName"));
            txtSName.setText(rs.getString("mName"));
            txtLName.setText(rs.getString("Lname"));
            
            String add6 = rs.getString("Gender");
                 if (add6.equals("Female")){
                  Male.setSelected(false);
                 Female.setSelected(true);
                 } else {
                 Female.setSelected(false);
                 Male.setSelected(true);
                }
            
            txtContactNo.setText((rs.getString("ContactNo")));
            txtEmail.setText((rs.getString("Email")));
            cboRank.setSelectedItem(rs.getString("rank"));
            txtShift.setSelectedItem(rs.getString("shift"));
            
            
            
             String dateValue2 = rs.getString("DOB"); // What ever column
                java.util.Date add12 = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue2);
                jDateChooser_DOB.setDate(add12);
                
                
                 String dateValue3 = rs.getString("DOB"); // What ever column
                java.util.Date add123 = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue3);
                jDateChooser_DOH.setDate(add123);
            
                
                 txtDesignation.setText((rs.getString("Des_Area")));
                 
                 txtpath.setText((rs.getString("photo")));
                 
                 //txtpath.setText(add14);
                filename=txtpath.getText();
       
                Icon icon = new ImageIcon(filename);
            
                 photo.setIcon(icon);

                 
          //  cbolegacytype.setSelectedItem(rs.getString("type_of_legacy"));
                 
                 
                 
            
            
            
            
           
        }
    } catch (Exception ex) {
        //Logger.getLogger(ExistingStock.class.getName()).log(Level.SEVERE, null, ex);
    }
    }//GEN-LAST:event_tblSearchMouseClicked

    private void btnViewPhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewPhotoActionPerformed
        // TODO add your handling code here:
        
        filename=txtpath.getText();
       
                Icon icon = new ImageIcon(filename);
            
                 photo.setIcon(icon);

    }//GEN-LAST:event_btnViewPhotoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInvestigatorOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInvestigatorOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInvestigatorOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInvestigatorOfficer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInvestigatorOfficer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Female;
    private javax.swing.ButtonGroup GenderSelect;
    private javax.swing.JRadioButton Male;
    private javax.swing.JButton btnAttach;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnTableSearch;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnViewPhoto;
    private javax.swing.JComboBox cboCriteria;
    private javax.swing.JComboBox cboLocations;
    private javax.swing.JComboBox cboRank;
    private javax.swing.JButton jButton1;
    private com.toedter.calendar.JDateChooser jDateChooser_DOB;
    private com.toedter.calendar.JDateChooser jDateChooser_DOH;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblCOntactNo;
    private javax.swing.JLabel lblCOntactNo1;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmail1;
    private javax.swing.JLabel lblFName;
    private javax.swing.JLabel lblFName1;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblGender1;
    private javax.swing.JLabel lblIOID;
    private javax.swing.JLabel lblIOID1;
    private javax.swing.JLabel lblLName;
    private javax.swing.JLabel lblLName1;
    private javax.swing.JLabel lblSName;
    private javax.swing.JLabel lblSName1;
    private javax.swing.JLabel lblTopName;
    private javax.swing.JLabel photo;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtContactNo;
    private javax.swing.JTextField txtCriterion;
    private javax.swing.JTextField txtDesignation;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFName;
    private javax.swing.JTextField txtIDNo;
    private javax.swing.JTextField txtIOID;
    private javax.swing.JTextField txtLName;
    private javax.swing.JTextField txtSName;
    private javax.swing.JTextField txtSearch1;
    private javax.swing.JComboBox txtShift;
    private javax.swing.JTextField txt_search;
    private javax.swing.JTextField txtpath;
    // End of variables declaration//GEN-END:variables
}
