
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Se STRANGE W
 */
public class frmInvestigationTable extends javax.swing.JFrame {
PreparedStatement pst=null;
ResultSet rs=null;
Connection conn=null;


    /**
     * Creates new form frmInvestigationTable
     */
    public frmInvestigationTable() {
        initComponents();
         conn = DatabaseConnection.ConnecrDb();
         
         txtSearched.setVisible(false);
         
         
         jDateChooser_DateOfCompletion.getJCalendar().setMaxSelectableDate(new Date());
         jDateChooser_DateOfStart.getJCalendar().setMaxSelectableDate(new Date());
    }
    
    
    
    public  void dateval()
            {
                
              
                
             
              
              
              
            }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel_Properties = new javax.swing.JPanel();
        lblSearch = new javax.swing.JLabel();
        txt_search = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtIOId = new javax.swing.JTextField();
        txtInv_RecordNo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        lblInvestigRecrod = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtCaseNo = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        lblInvestigationRecordNo = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txaReason = new javax.swing.JTextArea();
        jDateChooser_DateOfStart = new com.toedter.calendar.JDateChooser();
        jDateChooser_DateOfCompletion = new com.toedter.calendar.JDateChooser();
        cboState = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtSearched = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        update = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("INVESTIGATION REGISTER");

        jPanel3.setBackground(new java.awt.Color(102, 102, 255));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Investigation Register ");

        jPanel_Properties.setBackground(new java.awt.Color(150, 158, 153));
        jPanel_Properties.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Operations", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 3, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        lblSearch.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblSearch.setText("Please Use Inv Rec No to Search");

        txt_search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt_searchKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_searchKeyTyped(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon("C:\\CrpdasSystem\\images\\icons\\Search-icon.png")); // NOI18N
        jButton2.setText("Search");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_PropertiesLayout = new javax.swing.GroupLayout(jPanel_Properties);
        jPanel_Properties.setLayout(jPanel_PropertiesLayout);
        jPanel_PropertiesLayout.setHorizontalGroup(
            jPanel_PropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_PropertiesLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblSearch)
                .addGap(50, 50, 50))
            .addGroup(jPanel_PropertiesLayout.createSequentialGroup()
                .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_PropertiesLayout.setVerticalGroup(
            jPanel_PropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_PropertiesLayout.createSequentialGroup()
                .addComponent(lblSearch)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel_PropertiesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txt_search, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(150, 158, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Investigation Record Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("DATE OF START:");

        txtIOId.setToolTipText("type numbers only");
        txtIOId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtIOIdKeyTyped(evt);
            }
        });

        txtInv_RecordNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtInv_RecordNoKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("REASON OF INVESTIGATION");

        lblInvestigRecrod.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblInvestigRecrod.setText("INVESTIGATION");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("CASE NO:");

        txtCaseNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCaseNoKeyTyped(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("I/O ID:");

        lblInvestigationRecordNo.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblInvestigationRecordNo.setText("RECORD NO:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("DATE OF COMPLETION:");

        txaReason.setColumns(20);
        txaReason.setRows(5);
        txaReason.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txaReasonKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(txaReason);

        jDateChooser_DateOfStart.setToolTipText("Use the date format of \"yyyy-MM-dd\"");
        jDateChooser_DateOfStart.setDateFormatString("yyyy-MM-dd");

        jDateChooser_DateOfCompletion.setToolTipText("Use the date format of \"yyyy-MM-dd\"");
        jDateChooser_DateOfCompletion.setDateFormatString("yyyy-MM-dd");

        cboState.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Active", "Completed" }));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setText("State of Investivgation");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblInvestigRecrod)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(lblInvestigationRecordNo))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDateChooser_DateOfStart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtInv_RecordNo, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)
                            .addComponent(txtCaseNo)
                            .addComponent(txtIOId)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser_DateOfCompletion, javax.swing.GroupLayout.DEFAULT_SIZE, 162, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cboState, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel6))
                                .addGap(12, 12, 12)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(30, 30, 30))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblInvestigRecrod)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblInvestigationRecordNo))
                            .addComponent(txtInv_RecordNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cboState, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(txtCaseNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtIOId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jDateChooser_DateOfStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jDateChooser_DateOfCompletion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(22, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );

        jPanel2.setBackground(new java.awt.Color(150, 158, 153));

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon("C:\\CrpdasSystem\\images\\icons\\Save_icon.png")); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        clear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        clear.setText("CLEAR");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });

        update.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        update.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-file-icon.png"))); // NOI18N
        update.setText("UPDATE");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete1.jpg"))); // NOI18N
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(update, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(clear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(update)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(clear)
                .addGap(7, 7, 7)
                .addComponent(jButton3)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel_Properties, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(txtSearched, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(261, 261, 261))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel_Properties, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(73, 73, 73)
                .addComponent(txtSearched, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        setSize(new java.awt.Dimension(845, 445));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            
         if(txtInv_RecordNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Investigation Record Number","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtInv_RecordNo.requestFocus();
            
        }
        else  if(txtCaseNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Case Number ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtCaseNo.requestFocus();
            
            
            
        }
         else  if(txtIOId.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Investigation Officer Number  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtIOId.requestFocus();
           
        }
         
          else  if( txaReason.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Reason for investigation ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txaReason.requestFocus();
           
        }
          
          else  if( jDateChooser_DateOfStart.getDate()==null  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Select Date of Start  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txaReason.requestFocus();
           
        }
         
        else  if( jDateChooser_DateOfCompletion.getDate()==null  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Select Date of Completion  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txaReason.requestFocus();
           
        }  
        
          
        else
         {
        
        
        
        
        
        
         try {
            String sql = "Insert  into investigationrecord(Inv_RecordNo,CaseID,IO_ID,Date_Of_Start,Date_Of_Completion,Reason,state)values(?,?,?,?,?,?,?)";
            pst = conn.prepareStatement(sql);
            
            //PreparedStatement.RETURN_GENERATED_KEYS

            pst.setString(1, txtInv_RecordNo.getText());
            pst.setString(2, txtCaseNo.getText());
            pst.setString(3, txtIOId.getText());
            
            pst.setString(4, ((JTextField)jDateChooser_DateOfStart.getDateEditor().getUiComponent()).getText());
             pst.setString(5, ((JTextField)jDateChooser_DateOfCompletion.getDateEditor().getUiComponent()).getText());
           pst.setString(6,txaReason.getText());
        
            
           
           String dateds=cboState.getSelectedItem().toString();//ComboBox 
            pst.setString(7, dateds);

            pst.execute();
            
         

            JOptionPane.showMessageDialog(null, "Saved Succesfully");
            
           
        }
         catch (SQLException er) {
            
            JOptionPane.showMessageDialog(null, "The Data is already Saved you cannot save it again","CRPDS Message",JOptionPane.INFORMATION_MESSAGE);
        }
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        // TODO add your handling code here:
        txtInv_RecordNo.setText("");
        txtCaseNo.setText("");
        txtIOId.setText("");
        txaReason.setText("");
        
        
    }//GEN-LAST:event_clearActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        
          if(txtInv_RecordNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Investigation Record Number","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtInv_RecordNo.requestFocus();
            
        }
        else  if(txtCaseNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Case Number ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtCaseNo.requestFocus();
            
            
            
        }
         else  if(txtIOId.getText().equals("") )
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Investigation Officer Number  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtIOId.requestFocus();
           
        }
         
          else  if( txaReason.getText().equals("")  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Enter the Reason for investigation ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txaReason.requestFocus();
           
        }
          
          else  if( jDateChooser_DateOfStart.getDate()==null  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Select Date of Start  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txaReason.requestFocus();
           
        }
         
        else  if( jDateChooser_DateOfCompletion.getDate()==null  )// image.getText().isEmpty()
        {
            JOptionPane.showMessageDialog(null,"Please Select Date of Completion  ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txaReason.requestFocus();
           
        }  
        
          
        else
         {
        
        try {

            String value1 = txtInv_RecordNo.getText();
            String value2 = txtCaseNo.getText();
            String value3 = txtIOId.getText();
             
            //dates
            String value4=((JTextField)jDateChooser_DateOfStart.getDateEditor().getUiComponent()).getText();
            String value5=((JTextField)jDateChooser_DateOfCompletion.getDateEditor().getUiComponent()).getText();
            
            String value6 = txaReason.getText();
             String value7=cboState.getSelectedItem().toString(); 
             
             String searchn = txtSearched.getText();
            

            String sql = "update investigationrecord set Inv_RecordNo='" + value1 + "',CaseID='" + value2 + "',IO_ID='" + value3 + "',Date_Of_Start='" + value4 + "',Date_Of_Completion='" + value5 + "',Reason='" + value6 + "',state='"+value7+"' where Inv_RecordNo='" + searchn + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
         }
    }//GEN-LAST:event_updateActionPerformed

    private void txt_searchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyReleased

        
    }//GEN-LAST:event_txt_searchKeyReleased

    private void txt_searchKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_searchKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_searchKeyTyped

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 if(txt_search.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Investigation Record Number  to search","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txt_search.requestFocus();
        }
        else 
        {        // TODO add your handling code here:
        
        
        try {
            String sql = "select * from  investigationrecord where Inv_RecordNo=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txt_search.getText());

            rs = pst.executeQuery();
            if (rs.next()) {
                String add1 = rs.getString("Inv_RecordNo");
                txtInv_RecordNo.setText(add1);
                String add2 = rs.getString("CaseID");
                txtCaseNo.setText(add2);
                String add3 = rs.getString("IO_ID");
                txtIOId.setText(add3);
                String dateValue = rs.getString("Date_Of_Start"); // What ever column
                java.util.Date add4 = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue);
                jDateChooser_DateOfStart.setDate(add4);
                
                String dateValue2 = rs.getString("Date_Of_Completion"); // What ever column
                java.util.Date add5 = new SimpleDateFormat("yyyy-MM-dd").parse(dateValue2);
                jDateChooser_DateOfCompletion.setDate(add5);
                
                String add7 = rs.getString("Reason");
                txaReason.setText(add7);
                
                String pat2 = rs.getString("state");
                   cboState.addItem(pat2);
                
                
                String searched = rs.getString("Inv_RecordNo");
                txtSearched.setText(searched);
                

            }
            
             else
            {
                JOptionPane.showMessageDialog(null,"The Record has not been found","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        
        if(txtInv_RecordNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Type The Ivestigation Record Number you want to delete ");
        }
        else{
        
          int n=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete","CRPDAS",JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION)
        {
            
            String sql = "delete from  investigationrecord where Inv_RecordNo=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtInv_RecordNo.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        }
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void txtInv_RecordNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtInv_RecordNoKeyTyped
        // TODO add your handling code here:
        
        boolean max= txtInv_RecordNo.getText().length()>30;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtInv_RecordNoKeyTyped

    private void txtCaseNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCaseNoKeyTyped
        // TODO add your handling code here:
        
        boolean max= txtInv_RecordNo.getText().length()>30;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtCaseNoKeyTyped

    private void txtIOIdKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtIOIdKeyTyped
        // TODO add your handling code here:
         boolean max= txtInv_RecordNo.getText().length()>15;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
        
          if(   (!(Character.isDigit(evt.getKeyChar()))) &&  (!(Character.isSpaceChar(evt.getKeyChar()))) && (evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)  &&(evt.getKeyChar()!=KeyEvent.VK_DELETE)&& (evt.getKeyChar()!=KeyEvent.VK_ESCAPE)  )
        {
            evt.consume();
            
           JOptionPane.showMessageDialog(null, " Type Numbers  only","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        
        }
        
       
    }//GEN-LAST:event_txtIOIdKeyTyped

    private void txaReasonKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txaReasonKeyTyped
        // TODO add your handling code here:
        
        boolean max= txaReason.getText().length()>40;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txaReasonKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmInvestigationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmInvestigationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmInvestigationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmInvestigationTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmInvestigationTable().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cboState;
    private javax.swing.JButton clear;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private com.toedter.calendar.JDateChooser jDateChooser_DateOfCompletion;
    private com.toedter.calendar.JDateChooser jDateChooser_DateOfStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel_Properties;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblInvestigRecrod;
    private javax.swing.JLabel lblInvestigationRecordNo;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JTextArea txaReason;
    private javax.swing.JTextField txtCaseNo;
    private javax.swing.JTextField txtIOId;
    private javax.swing.JTextField txtInv_RecordNo;
    private javax.swing.JTextField txtSearched;
    private javax.swing.JTextField txt_search;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables
}
