
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.draw.DottedLineSeparator;
import com.itextpdf.text.pdf.draw.VerticalPositionMark;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Date;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Se STRANGE W
 */
public class frmJails extends javax.swing.JFrame {
Connection conn = null;//name of intialized conn
    PreparedStatement pst = null;
    ResultSet rs = null;
    /**
     * Creates new form frmJails
     */
    public frmJails() {
        initComponents();
        txtJailNoSrch.setVisible(false);
        
        conn = DatabaseConnection.ConnecrDb();
        
        btnReport.setVisible(false);
        jButton1.setVisible(false);
        jButton2.setVisible(false);
    }
    
    public void clear()
    {
    txtJailNo.setText("");
    txtJailName.setText("");
    cboJailType.addItem("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        txtJailNoSrch = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        cboJailType = new javax.swing.JComboBox();
        txtJailName = new javax.swing.JTextField();
        lblJailName = new javax.swing.JLabel();
        txtJailNo = new javax.swing.JTextField();
        lblJailType = new javax.swing.JLabel();
        lblJailNo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("JAIL FORM");

        jPanel4.setBackground(new java.awt.Color(102, 102, 255));

        jPanel3.setBackground(new java.awt.Color(150, 158, 153));

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search-icon.png"))); // NOI18N
        btnSearch.setText("SEARCH");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setText("Please Use Jail Number to search");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnSearch)
                .addGap(0, 13, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearch)))
        );

        jPanel1.setBackground(new java.awt.Color(150, 158, 153));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Jail Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        cboJailType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Maximum", "Minimum", "Juvenile", "Federal", "State" }));

        txtJailName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJailNameKeyTyped(evt);
            }
        });

        lblJailName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblJailName.setText("JAIL NAME:");

        txtJailNo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtJailNoKeyTyped(evt);
            }
        });

        lblJailType.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblJailType.setText("JAIL TYPE:");

        lblJailNo.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblJailNo.setText("JAIL NUMBER:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblJailName)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblJailNo, javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(19, 19, 19)
                            .addComponent(lblJailType))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtJailNo)
                    .addComponent(txtJailName)
                    .addComponent(cboJailType, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJailNo)
                    .addComponent(txtJailNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJailName)
                    .addComponent(txtJailName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJailType)
                    .addComponent(cboJailType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBackground(new java.awt.Color(150, 158, 153));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buttons", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(0, 0, 204))); // NOI18N

        btnUpdate.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnUpdate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/edit-file-icon.png"))); // NOI18N
        btnUpdate.setText("UPDATE ");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnClear.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnClear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/clear.png"))); // NOI18N
        btnClear.setText("CLEAR ");

        btnSave.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Save_icon.png"))); // NOI18N
        btnSave.setText("SAVE");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/delete1.jpg"))); // NOI18N
        btnDelete.setText("DELETE ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnUpdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnClear, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnClear, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Jail Register ");

        jButton1.setText("Report ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("IReport ");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        btnReport.setText("REPORT");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(txtJailNoSrch, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnReport)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(181, 181, 181)
                                .addComponent(jLabel1)
                                .addGap(14, 14, 14)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(19, 19, 19)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtJailNoSrch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(89, 89, 89))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(655, 326));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        
         if(txtJailNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Jail No","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtJailName.requestFocus();
            
        }
        else  if(txtJailName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Jail Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtJailName.requestFocus();
            
            
            
        }
        else 
        {
        
        
         try {
            String sql = "Insert  into jail(JailNo,JailName,JailType) values(?,?,?)";
            pst = conn.prepareStatement(sql);
            
             pst.setString(1, txtJailNo.getText());
            pst.setString(2, txtJailName.getText());
           // pst.setString(3, cboJailType.getText());
            
            String value=cboJailType.getSelectedItem().toString();//ComboBox 
            pst.setString(3, value);
            
           pst.execute();
            JOptionPane.showMessageDialog(null, "Saved Succesfully");
            
           
        }
         catch (SQLException er) {
            
            JOptionPane.showMessageDialog(null, "The Data is already Saved you cannot save it again","CRPDS Message",JOptionPane.INFORMATION_MESSAGE);
        }
         
         catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
         
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed

        
        if(txtJailNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please Type The Jail Number you want to delete ");
        }
        else{
        
         int n=JOptionPane.showConfirmDialog(null, "Are you sure you want to delete","CRPDAS",JOptionPane.YES_NO_OPTION);
        if(n==JOptionPane.YES_OPTION)
        {
        String sql = "delete from jail where JailNo=?";

        try {
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtJailNo.getText());
            pst.execute();
            JOptionPane.showMessageDialog(null, "Deleted");
            clear();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        }
        
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        
        String value1=txtJailNo.getText();
        String value2=txtJailName.getText();
        String Value3= cboJailType.getSelectedItem().toString();
        
        
        try
        {
       Document document= new Document();
        PdfWriter.getInstance(document,new FileOutputStream("JailsReport.pdf"));
        
        document.open();
        
        
        
        
        Image image =Image.getInstance("images/policekenyalogo.jpg");
        float leftMargin = document.leftMargin();
        float rightMargin = document.rightMargin();
        float pageSize = document.getPageSize().getWidth();
            float _textIndent = 0;
        float usablePageSize = pageSize - (rightMargin + leftMargin + _textIndent);
        float imageWidth = image.getAbsoluteX();
        
        
        if (imageWidth > usablePageSize)
{
        float reduceWidth = imageWidth - usablePageSize;
        float reducePercent = 100f - ((reduceWidth * 100f) / imageWidth);
        image.scalePercent(reducePercent);
        image.setAlignment(Image.RIGHT);
}
                       

else
{
        image.setAlignment(Image.MIDDLE);
        image.setIndentationLeft(_textIndent);
} 
                      
        //document.add( new Paragraph("Image"));
        document.add(image);
        
        
        Chunk glue = new Chunk(new VerticalPositionMark());
        Paragraph p = new Paragraph("Jails Report",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.RED));
         p.add(new Chunk(glue));
         document.add(p);
       // document.add(p);
        //document.add(new Paragraph("Jails Report",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.RED)));
        //document.add(new Paragraph("This is Report......................"));
         Chunk glued = new Chunk(new VerticalPositionMark());
        Paragraph pp = new Paragraph();
         pp.add(new Chunk(glued));
        pp.add(  new Date().toString());
         document.add(pp);
        
        document.add(new Paragraph(" "));
        //Chunk glue = new Chunk(new VerticalPositionMark());
        //Paragraph p = new Paragraph("Text to8,Font.BOLD,BaseColor.RED)) the left");
        //p.add(new Chunk(glue));
        
       // document.add(new Paragraph("Walter "));
        //p.add("Text to the right");
        //document.add(p);
        
        
        
        JOptionPane.showMessageDialog(null, "Report Saved");
        
        
            PdfPTable table = new PdfPTable(2);
           /* PdfPCell cells = PdfPCell( new Paragraph("Title"));
            cells.setColspan(4);
            cells.setHorizontalAlingment(Element.ALIGN_CENTER);
            cells.setBackgroundColor(Color.BLUE);
            table.addCell(cells);*/
           
            
            table.addCell("Jail Number");//PdfPCell.ALIGN_CENTER
            table.addCell(value1);
            
            table.addCell("Name");
            table.addCell(value2);
            table.addCell("Type");
            table.addCell(Value3);
            
            document.add(table);
            
           // com.itextpdf.text.List list= new com.itextpdf.text.List(true,20);
            //list.add("First Item");
            //list.add("Second Item");
            //list.add("Third Element");
           // document.add(list);
            
            document.add(new Paragraph("CPAS System @2017"));
            document.add(new Paragraph(""));
            //document.add(new Paragraph(".........................................................................................................................................................."));
            
            Chunk linebreak = new Chunk(new DottedLineSeparator());
            document.add(linebreak); 
        document.close();
        }
        catch(Exception ex )
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnReportActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        
         if(txtJailNo.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Jail No","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtJailName.requestFocus();
            
        }
        else  if(txtJailName.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Jail Name ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtJailName.requestFocus();
            
            
            
        }
        else 
        {
        
         try {

            String value1 = txtJailNo.getText();
            String value2 = txtJailName.getText();
            String value3=cboJailType.getSelectedItem().toString(); 
            
             String searchn = txtJailNoSrch.getText();
            

            String sql = "update  jail set JailNo='" + value1 + "',JailName='" + value2 + "',JailType='" + value3 + "' where JailNo='" + searchn + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            JOptionPane.showMessageDialog(null, "Updated");

        } catch (SQLException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, e);
        }
         
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
         if(txtSearch.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Jail Number    to search record ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
            txtSearch.requestFocus();
        }
        else 
        {
         try {
            String sql = "select * from  jail where JailNo=?";
            pst = conn.prepareStatement(sql);
            pst.setString(1, txtSearch.getText());

            rs = pst.executeQuery();
            
            if (rs.next()) {
                String add1 = rs.getString("JailNo");
                txtJailNo.setText(add1);
                String add2 = rs.getString("JailName");
                txtJailName.setText(add2);
                String addcon=rs.getString("JailType");
                cboJailType.setSelectedItem(addcon);
                
                
                String addSrch = rs.getString("JailNo");
                txtJailNoSrch.setText(addSrch);

        
                 }
            
             else
            {
                JOptionPane.showMessageDialog(null,"The Record has not been found","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            }


                } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
                }
        }
        
        
    }//GEN-LAST:event_btnSearchActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
         
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        
          try
        {
          
            
            //String report="C:\\Users\\Se STRANGE W\\Documents\\reported\\jailsReports.jrxml";
            
           
            JasperDesign jd= JRXmlLoader.load("C:\\Users\\Se STRANGE W\\Documents\\reported\\jailsReports.jrxml");
             String sql="select * FROM jail ";
             JRDesignQuery  newQuery = new  JRDesignQuery();
             newQuery.setText(sql);
             jd.setQuery(newQuery);
             
            JasperReport  jr=JasperCompileManager.compileReport(jd);
            JasperPrint jp= JasperFillManager.fillReport(jr,null,conn);
            JasperViewer.viewReport(jp);
            
            
            
            
        }
        catch(Exception e)
        {
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void txtJailNoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJailNoKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtJailNo.getText().length()>10;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
        
        
        if(   (!(Character.isDigit(evt.getKeyChar()))) &&  (!(Character.isSpaceChar(evt.getKeyChar()))) && (evt.getKeyChar()!=KeyEvent.VK_BACK_SPACE)  &&(evt.getKeyChar()!=KeyEvent.VK_DELETE)&& (evt.getKeyChar()!=KeyEvent.VK_ESCAPE)  )
        {
            evt.consume();
            
           JOptionPane.showMessageDialog(null, "Numbers only  i.e 0-9","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
   
        
        }
    }//GEN-LAST:event_txtJailNoKeyTyped

    private void txtJailNameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtJailNameKeyTyped
        // TODO add your handling code here:
        
         boolean max= txtJailName.getText().length()>30;
        if(max)
        {
            evt.consume();
            JOptionPane.showMessageDialog(null, "Limit of charcters reached ","CRPDAS",JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_txtJailNameKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmJails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmJails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmJails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmJails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmJails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnUpdate;
    public javax.swing.JComboBox cboJailType;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblJailName;
    private javax.swing.JLabel lblJailNo;
    private javax.swing.JLabel lblJailType;
    public javax.swing.JTextField txtJailName;
    public javax.swing.JTextField txtJailNo;
    private javax.swing.JTextField txtJailNoSrch;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
