
//import static com.sun.corba.se.spi.presentation.rmi.StubAdapter.request;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Se STRANGE W
 */
public class frmLogin extends javax.swing.JFrame {
 Connection conn=null;
 ResultSet rs=null;
 PreparedStatement pst=null;
 
 
    /**
     * Creates new form frmLogin
     */
    public frmLogin() {
        initComponents();
        
        conn=DatabaseConnection.ConnecrDb();
        
        txtUserlogin.setVisible(false);
        
    }
    
    
   /* private void  locked()
        
{
    frmHome s= new frmHome();
    s.mnregisters.setVisible(false);
    s.mnReports.setVisible(false);
    s.mnUsers.setVisible(false);
    
    s.btnLogout.setVisible(false);
    s.JMIStaff.setVisible(false);
    s.JMIAdminstrator.setVisible(false);
    s.jMenuItem1.setVisible(false);
    s.mnRJails.setVisible(false);
    
    s.jMenuItem3.setVisible(false);
    s.jMenuItem4.setVisible(false);
    s.jMenuItem5.setVisible(false);
    s.jmiAccomplisher.setVisible(false);
    s.jmiAccused.setVisible(false);
    s.jmiAccused.setVisible(false);
    s.jmiInvestigator.setVisible(false);
    s.jmiVictim.setVisible(false);
    s.jmnInvestigation.setVisible(false);
    s.mnHelp.setVisible(false);
    s.mnReports.setVisible(false);
    
    s.mnUsers.setVisible(false);
    s.mnregisters.setVisible(false);
    
    
    s.jmiAccomplisher.setEnabled(false);
    
    
}*/
    
    
    
    private void loginNumber()
            
    {
        
        /* try {
                             String sqld = "Insert  into logs_successfull(UserID,password)values(?,?)";
                             pst = conn.prepareStatement(sqld);

                             pst.setString(1, txtUsername.getText());
                             pst.setString(2, pswPasssword.getText());
                             
                             
            
                              pst.execute();

            

                                 } catch (Exception ea) {
                           
                                }
       
                        
            
            }*/
            
            
    }
public void close()
{
    WindowEvent winClosingEvent=new WindowEvent(this,WindowEvent.WINDOW_CLOSED);
    Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
}




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lblClose = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lblPassword = new javax.swing.JLabel();
        txtUsername = new javax.swing.JTextField();
        lblUsername = new javax.swing.JLabel();
        pswPasssword = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        lblReset = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        txtUserlogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("LOGIN FORM");

        jPanel2.setBackground(new java.awt.Color(51, 51, 255));
        jPanel2.setForeground(new java.awt.Color(51, 51, 255));

        lblClose.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblClose.setIcon(new javax.swing.ImageIcon("C:\\Users\\Se STRANGE W\\Documents\\NetBeansProjects\\CRIME MANAGEMENT INFORMATION SYSTEM\\images\\icons\\close.png")); // NOI18N
        lblClose.setText("Close Application ");
        lblClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblCloseActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "LogIn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Telenor", 1, 18), new java.awt.Color(0, 0, 153))); // NOI18N

        lblPassword.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(0, 0, 153));
        lblPassword.setText("PASSWORD:");

        lblUsername.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblUsername.setForeground(new java.awt.Color(0, 0, 153));
        lblUsername.setText("USERNAME:");

        btnLogin.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/App-login-manager-icon - Copy.png"))); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        btnRefresh.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnRefresh.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Refresh-icon.png"))); // NOI18N
        btnRefresh.setText("Refresh");

        lblReset.setBackground(new java.awt.Color(0, 0, 204));
        lblReset.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        lblReset.setForeground(new java.awt.Color(0, 0, 204));
        lblReset.setText("Reset your Password/Username");
        lblReset.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblResetMouseClicked(evt);
            }
        });
        lblReset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lblResetKeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Apps-Computer-Login-icon.png"))); // NOI18N
        jLabel1.setText("jLabel1");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Help-icon.png"))); // NOI18N
        jLabel2.setText("Help");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel2MouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });
        jLabel2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jLabel2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addGap(18, 18, 18)
                        .addComponent(lblReset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnLogin))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblPassword)
                            .addComponent(lblUsername))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pswPasssword, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(txtUsername))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtUserlogin, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(25, 25, 25))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtUserlogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUsername)
                    .addComponent(txtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(pswPasssword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLogin)
                    .addComponent(lblReset)
                    .addComponent(btnRefresh, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblClose)
                .addGap(126, 126, 126))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblCloseActionPerformed
       // close();        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_lblCloseActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed

        
         if(txtUsername.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter Username","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtUsername.requestFocus();
            
        }
        else  if(pswPasssword.getText().equals(""))
        {
            JOptionPane.showMessageDialog(null,"Please Enter  Your Password ","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            pswPasssword.requestFocus();
            
            
            
        }
        
       
        else 
        {
        String sql="select * from staff where UserID=? AND Status=1 and password=? ";
        
        try
        {
            pst=conn.prepareStatement(sql);
            pst.setString(1, txtUsername.getText());
            pst.setString(2, pswPasssword.getText());
 
            rs=pst.executeQuery();
            
            if(rs.next())
            {
             
             String username=rs.getString("UserID");
             String password=rs.getString("Password");
             String typeUser=rs.getString("Previlages");
             String username1=txtUsername.getText();
             String password2=pswPasssword.getText();
               
                  String set=rs.getString("setby");
                 String str1 ="Standard";
                 String str2="Admin";
                 txtUserlogin.setText(typeUser);
                 
                 
                
               if(   (str2.equals(set))   &&  (username.equals(username1)) && (password.equals(password2))  )
               {
                       
                   JOptionPane.showMessageDialog(null,"Login succesfull!!!!");
                         dispose();
                        //locked();//Method to lock all JMenus
                         frmNewPassword n= new frmNewPassword();
                        n.setVisible(true);   
               }
               
               else if((str1.equals(set))      &&  (username.equals(username1)) && (password.equals(password2))  )
               {
                   
                   
                   frmHome s =new frmHome();
                   frmHome.txtUserType.setText(this.txtUserlogin.getText());
                        s.setVisible(true); 
                        dispose();
                        
                        
                        
                          //frmHome nf1 = new frmHome();
                          
                          
        
                        
               }
               else
               {
                   JOptionPane.showMessageDialog(null,"Username or password is inccorect  "); 
               }
                   
                 
                        
               
               
               
               
               
                          try {
                             String sqld = "Insert  into logs_successfull(UserID,password)values(?,?)";
                             pst = conn.prepareStatement(sqld);

                             pst.setString(1, txtUsername.getText());
                             pst.setString(2, pswPasssword.getText());
            
                              pst.execute();

            

                                 } catch (Exception ea) {
                           JOptionPane.showMessageDialog(null, "There is a problem in logs.Inform the Adminstrator");
                                }
       
                        
            
            }
            
            else 
            {
                JOptionPane.showMessageDialog(null,"Username or password is inccorect ");
                
                
                
                
                 //LOGS aLL aTTEMPTS
                                
                               try {
                             String sqld = "Insert  into  log_attempt(UserID,password_attempt)values(?,?)";
                             pst = conn.prepareStatement(sqld);

                             pst.setString(1, txtUsername.getText());
                             pst.setString(2, pswPasssword.getText());
            
                              pst.execute();

            

                                 } catch (Exception ea) {
                           JOptionPane.showMessageDialog(null, "There is a problem in logs.Inform the Adminstrator");
                                }
                
                
                
                
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null,e);
        }
        
        
                              
        }
        
    }//GEN-LAST:event_btnLoginActionPerformed

    private void lblResetKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblResetKeyPressed
        // TODO add your handling code here:
        //new frmReset().setVisible(true);
    }//GEN-LAST:event_lblResetKeyPressed

    private void lblResetMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblResetMouseClicked
        // TODO add your handling code here:
        dispose();
         new frmResetChooser().setVisible(true);
         
    }//GEN-LAST:event_lblResetMouseClicked

    private void jLabel2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel2KeyTyped
        // TODO add your handling code here:
        
         

        
    }//GEN-LAST:event_jLabel2KeyTyped

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        
         if(Desktop.isDesktopSupported())
{
           try {
               Desktop.getDesktop().browse(new URI("http://localhost/Help_crpds/"));
           } catch (IOException ex) {
               Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
           } catch (URISyntaxException ex) {
               Logger.getLogger(frmHome.class.getName()).log(Level.SEVERE, null, ex);
           }
}
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MousePressed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_jLabel2MousePressed

    private void jLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseEntered
        // TODO add your handling code here:
        
        jLabel2.setForeground(Color.WHITE);
    }//GEN-LAST:event_jLabel2MouseEntered

    private void jLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseExited
        // TODO add your handling code here:
        
        jLabel2.setForeground(Color.BLUE);
    }//GEN-LAST:event_jLabel2MouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
               /* if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                
                UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton lblClose;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblReset;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField pswPasssword;
    public static javax.swing.JTextField txtUserlogin;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
