
import com.itextpdf.kernel.color.Color;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Document;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Image;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfContentByte;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.draw.DottedLineSeparator;
import com.itextpdf.text.pdf.draw.VerticalPositionMark;
import java.awt.Graphics2D;
import java.awt.Shape;
import java.io.FileOutputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
//import javax.swing.text.Document;
import net.proteanit.sql.DbUtils;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Se STRANGE W
 */
public class frmSrchJails extends javax.swing.JFrame {

    /**
     * Creates new form frmSrchJails
     */
    
    Connection conn = null;//name of intialized conn
    PreparedStatement pst = null;
    ResultSet rs = null;
    public frmSrchJails() {
        initComponents();
        
         conn = DatabaseConnection.ConnecrDb();
    }
frmJails jailed = new frmJails();
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlJailSrch = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Jail = new javax.swing.JTable();
        btnSearch = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        btnReport = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("REPORT JAIL FORM");

        pnlJailSrch.setBackground(new java.awt.Color(153, 153, 255));

        tbl_Jail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Jail Number", "Jail Name", "Jail Type"
            }
        ));
        tbl_Jail.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_JailMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_Jail);

        btnSearch.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Search-icon.png"))); // NOI18N
        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jButton1.setText("Jail Report ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btnReport.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        btnReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Report1.jpg"))); // NOI18N
        btnReport.setText("Generate Report ");
        btnReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlJailSrchLayout = new javax.swing.GroupLayout(pnlJailSrch);
        pnlJailSrch.setLayout(pnlJailSrchLayout);
        pnlJailSrchLayout.setHorizontalGroup(
            pnlJailSrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJailSrchLayout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch)
                .addGap(29, 29, 29)
                .addComponent(btnReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlJailSrchLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 629, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlJailSrchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );
        pnlJailSrchLayout.setVerticalGroup(
            pnlJailSrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlJailSrchLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlJailSrchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReport))
                .addGap(24, 24, 24)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlJailSrch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlJailSrch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbl_JailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_JailMouseClicked
        int index= tbl_Jail.getSelectedRow();
        TableModel model= tbl_Jail.getModel();
        String JailNo=model.getValueAt(index, 0).toString();
        String JName=model.getValueAt(index, 1).toString();
        String JType=model.getValueAt(index, 2).toString();
        

        jailed.setVisible(true);
        jailed.pack();
        jailed.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        jailed.setLocationRelativeTo(null);

        jailed.txtJailNo.setText(JailNo);
        jailed.txtJailName.setText(JName);
       // jailed.cboJailType.setText(JType);
        
        jailed.cboJailType.setSelectedItem(JType);
       
        /*
        */

        dispose();

    }//GEN-LAST:event_tbl_JailMouseClicked

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:

        try{
                
            
            String sql="select JailNo,JailName,JailType from jail where JailNo=?";
            pst=conn.prepareStatement(sql);
            pst.setString(1, txtSearch.getText());
            
            
            rs=pst.executeQuery();
            
            
          
            
                tbl_Jail.setModel(DbUtils.resultSetToTableModel(rs));
            
            
            
            
             
        }
            catch( Exception e )
            {
                JOptionPane.showMessageDialog(null, e);

            }

    }//GEN-LAST:event_btnSearchActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    private void btnReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportActionPerformed
        // TODO add your handling code here:
        
        
        
        try
        {
       Document document= new Document();
        PdfWriter.getInstance(document,new FileOutputStream("JailReport.pdf"));
        
        document.open();
        
        
        Image image =Image.getInstance("reportimg.jpg");
        document.add( new Paragraph("Image"));
        document.add(image);
        
        document.add(new Paragraph("Welcome to The future ",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.RED)));
        document.add(new Paragraph("This is Report......................"));
        document.add(new Paragraph(new Date().toString()));
        JOptionPane.showMessageDialog(null, "Report Saved");
        
        
            PdfPTable table = new PdfPTable(2);
           /* PdfPCell cells = PdfPCell( new Paragraph("Title"));
            cells.setColspan(4);
            cells.setHorizontalAlingment(Element.ALIGN_CENTER);
            cells.setBackgroundColor(Color.BLUE);
            table.addCell(cells);*/
           
            
            table.addCell("Item1");
            table.addCell("Item2");
            table.addCell("Item3");
            table.addCell("Item4");
            
            document.add(table);
            
            com.itextpdf.text.List list= new com.itextpdf.text.List(true,20);
            list.add("First Item");
            list.add("Second Item");
            list.add("Third Element");
            document.add(list);
            
            
        document.close();
        }
        catch(Exception ex )
        {
            JOptionPane.showMessageDialog(null, ex);
        }
    }//GEN-LAST:event_btnReportActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        
        
         Document document = new Document(PageSize.A4.rotate());
    try {
        
        
             
     
      PdfWriter writer = PdfWriter.getInstance(document, new FileOutputStream("jTable.pdf"));
      

      document.open();
      
       Image image =Image.getInstance("images/policekenyalogo.jpg");
        float leftMargin = document.leftMargin();
        float rightMargin = document.rightMargin();
        float pageSize = document.getPageSize().getWidth();
            float _textIndent = 0;
        float usablePageSize = pageSize - (rightMargin + leftMargin + _textIndent);
        float imageWidth = image.getAbsoluteX();
        
        
        if (imageWidth > usablePageSize)
{
        float reduceWidth = imageWidth - usablePageSize;
        float reducePercent = 100f - ((reduceWidth * 100f) / imageWidth);
        image.scalePercent(reducePercent);
        image.setAlignment(Image.RIGHT);
}
                       

else
{
        image.setAlignment(Image.MIDDLE);
        image.setIndentationLeft(_textIndent);
} 
                      
        //document.add( new Paragraph("Image"));
        document.add(image);
      
      
      
       Chunk glue = new Chunk(new VerticalPositionMark());
        Paragraph p = new Paragraph("Jails Report",FontFactory.getFont(FontFactory.TIMES_BOLD,18,Font.BOLD,BaseColor.RED));
         p.add(new Chunk(glue));
         document.add(p);
         
         Chunk glued = new Chunk(new VerticalPositionMark());
        Paragraph pp = new Paragraph();
         pp.add(new Chunk(glued));
        pp.add(  new Date().toString());
         document.add(pp);
        
        document.add(new Paragraph(" "));
        
         
         
      PdfContentByte cb = writer.getDirectContent();

      cb.saveState();
      Graphics2D g2 = cb.createGraphics(500, 500);

      Shape oldClip = g2.getClip();
      g2.clipRect(10, 0, 500, 500);

      tbl_Jail.print(g2);
      g2.setClip(oldClip);

      g2.dispose();
      cb.restoreState();
      
       
            document.add(new Paragraph(""));
            //document.add(new Paragraph(".........................................................................................................................................................."));
            
            Chunk linebreak = new Chunk(new DottedLineSeparator());
            document.add(linebreak); 
            document.add(new Paragraph(""));
      document.add(new Paragraph("CPAS System @2017"));
        JOptionPane.showMessageDialog(null, "Report Saved");
    } catch (Exception e) {
      System.err.println(e.getMessage());
    }
    document.close();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmSrchJails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmSrchJails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmSrchJails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmSrchJails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmSrchJails().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReport;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlJailSrch;
    private javax.swing.JTable tbl_Jail;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
