
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.data.JRTableModelDataSource;
import net.sf.jasperreports.view.JRViewer;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Se STRANGE W
 */
public class rpt_Anlyz_Totals extends javax.swing.JFrame {

    /**
     * Creates new form rpt_Anlyz_Totals
     */
    
    PreparedStatement pst=null;
ResultSet rs=null;
Connection conn=null;
    public rpt_Anlyz_Totals() {
        initComponents();
        
         conn = DatabaseConnection.ConnecrDb();
         
         Fill_location();
         
         dateFrom.getJCalendar().setMaxSelectableDate(new Date());
         dateTo.getJCalendar().setMaxSelectableDate(new Date());
         
         pnldisp.setVisible(false);
    }
    
    
     private void Fill_location()
    {
        try {
            
            String sql="select * from locations";
            pst = conn.prepareStatement(sql);
            rs=pst.executeQuery();
            
            while(rs.next())
            {
                String location=rs.getString("LocationName");
                cboLocations.addItem(location);
                
                        
            }
                
            
        } catch (Exception e) {
            
            JOptionPane.showMessageDialog(null, e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSearch = new javax.swing.JTable();
        cboSelect = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        pnldisp = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        dateFrom = new com.toedter.calendar.JDateChooser();
        dateTo = new com.toedter.calendar.JDateChooser();
        cboLocations = new javax.swing.JComboBox();
        cboCrime = new javax.swing.JComboBox();
        btnReports = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        pnlSuspectID = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("TOTAL ANALYSIS REPORT");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Please Select the Total Summary to find");

        tblSearch.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(tblSearch);

        cboSelect.setEditable(true);
        cboSelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Suspect Cases", "Crimes in Area", " " }));
        cboSelect.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cboSelectItemStateChanged(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Analyis2.png"))); // NOI18N
        jButton1.setText("Analyze");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        pnldisp.setBackground(new java.awt.Color(153, 153, 153));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel4.setText("To:");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Select Location");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("From:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Crime Type");

        dateFrom.setDateFormatString("yyyy-MM-dd");

        dateTo.setDateFormatString("yyyy-MM-dd");

        cboCrime.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Assult", "Stilling", "Homicide", "Rape", "Sexual Harrasment ", "Accident", "Riot", " " }));

        javax.swing.GroupLayout pnldispLayout = new javax.swing.GroupLayout(pnldisp);
        pnldisp.setLayout(pnldispLayout);
        pnldispLayout.setHorizontalGroup(
            pnldispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldispLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnldispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldispLayout.createSequentialGroup()
                        .addComponent(cboLocations, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnldispLayout.createSequentialGroup()
                        .addComponent(cboCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(pnldispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(pnldispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        pnldispLayout.setVerticalGroup(
            pnldispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnldispLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnldispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnldispLayout.createSequentialGroup()
                        .addGroup(pnldispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cboLocations, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnldispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cboCrime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnldispLayout.createSequentialGroup()
                        .addGroup(pnldispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(dateFrom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(pnldispLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(dateTo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnReports.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnReports.setIcon(new javax.swing.ImageIcon("C:\\CrpdasSystem\\images\\icons\\Report1.jpg")); // NOI18N
        btnReports.setText("Generate Report");
        btnReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReportsActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Location/Suspect Total Summary Analyisis   Report");

        pnlSuspectID.setBackground(new java.awt.Color(153, 153, 153));

        txtSearch.setToolTipText("type suspect's ID\n");
        txtSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSearchActionPerformed(evt);
            }
        });

        jLabel6.setText("Type Suspect ID No to Analyze");

        javax.swing.GroupLayout pnlSuspectIDLayout = new javax.swing.GroupLayout(pnlSuspectID);
        pnlSuspectID.setLayout(pnlSuspectIDLayout);
        pnlSuspectIDLayout.setHorizontalGroup(
            pnlSuspectIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlSuspectIDLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlSuspectIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnlSuspectIDLayout.setVerticalGroup(
            pnlSuspectIDLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlSuspectIDLayout.createSequentialGroup()
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(pnldisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(cboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(pnlSuspectID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReports))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel15)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cboSelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnReports))
                    .addComponent(pnlSuspectID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(pnldisp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(6, 6, 6))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
    if((cboSelect.getSelectedItem().equals("Suspect Cases"))&& pnlSuspectID.isVisible())
        {
            
           
            if(txtSearch.getText().equals(""))
            {
            JOptionPane.showMessageDialog(null,"Please Enter Suspect's  ID to search","CRPDAS Message",JOptionPane.INFORMATION_MESSAGE);
            txtSearch.requestFocus();
            }
            else 
            {
        
                try {
                        String sql = "select * from   suspect_case_totals where AccusedID ='"+txtSearch.getText()+"'";
            
                        pst=conn.prepareStatement(sql);
                        rs=pst.executeQuery();
                        tblSearch.setModel(DbUtils.resultSetToTableModel(rs));
                    }
                    catch(Exception ex)
             
                     {
                     JOptionPane.showMessageDialog(null,ex);
                    }
             }
             
        }
    
    else if((cboSelect.getSelectedItem().equals("Crimes in Area")))
        
    {
        
        if(dateFrom.getDate()==null&& dateFrom.getDate()==null)
        {
            JOptionPane.showMessageDialog(null, "The Dates  from/to has not been selected ","CRPDAS Message ",JOptionPane.INFORMATION_MESSAGE);
        }
        
        else
        {
            
        
          
        String Location;
        String CrimeType;
         Location=(String) cboLocations.getSelectedItem();
         CrimeType=(String) cboCrime.getSelectedItem();
         
         java.util.Date jd= dateFrom.getDate();
        java.util.Date jd1=dateTo.getDate();
        
        
         try{
        
         String sql="select  place_of_incident, count(*) AS Total from  fir  where  Date_Filled between  ? and ? and place_of_incident='"+Location+"' and CrimeType='"+CrimeType+"' "; 
         
         pst=conn.prepareStatement(sql);
            pst.setDate(1, new java.sql.Date(jd.getTime()));
            pst.setDate(2,new java.sql.Date(jd1.getTime()));
            
            rs=pst.executeQuery();
            tblSearch.setModel(DbUtils.resultSetToTableModel(rs));
         
         
         }
         catch(Exception ed)
             
                 {
                 
                 }
            
    }
    }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cboSelectItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cboSelectItemStateChanged
        // TODO add your handling code here:
        
        if(cboSelect.getSelectedItem().equals("Suspect Cases"))
        {
            pnldisp.setVisible(false);
            pnlSuspectID.setVisible(true);
            
        }
        else if(cboSelect.getSelectedItem().equals("Crimes in Area"))
        {
            pnldisp.setVisible(true);
            
            pnlSuspectID.setVisible(false);
        }
         else if(cboSelect.getSelectedItem().equals("Accomplishers Total"))
        {
            pnldisp.setVisible(false);
            txtSearch.setVisible(true);
        }       
                
        
        
    }//GEN-LAST:event_cboSelectItemStateChanged

    private void btnReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReportsActionPerformed
        // TODO add your handling code here:
        
       
        
        if( cboSelect.getSelectedItem().equals("Crimes in Area" ) )
        {
           
             try
            {
                
                //DefaultTableModel
                DefaultTableModel de=(DefaultTableModel) tblSearch.getModel();
                JRTableModelDataSource  datasource = new JRTableModelDataSource(de);
                String  reportsource="C:\\CrpdasSystem\\reported\\rptCrimeTotalsAnalysis.jrxml";
                JasperReport  jr=JasperCompileManager.compileReport(reportsource);
                Map<String,Object> params = new HashMap<String, Object>();
                params.put("title1","title2");
                
                JasperPrint jp= JasperFillManager.fillReport(jr,params,datasource);
                //JasperViewer.viewReport(jp);
                
                JFrame frame = new JFrame("Reports");
                frame.getContentPane().add(new JRViewer(jp));
                frame.pack();
                frame.setSize(1000, 650);
                frame.setLocationRelativeTo(this);
                frame.setVisible(true);
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"No record on table . to be displayed...Please Search record before trying generating report\n If Problem persist contact adminstratior ");
                
                //JOptionPane.showMessageDialog(null,e);
            }
             
        }
             
             else if(cboSelect.getSelectedItem().equals("Suspect Cases" ))
                     {
                     
                         try
            {
                
                //DefaultTableModel
                DefaultTableModel de=(DefaultTableModel) tblSearch.getModel();
                JRTableModelDataSource  datasource = new JRTableModelDataSource(de);
                String  reportsource="C:\\CrpdasSystem\\reported\\rptSummSuspectCrimes.jrxml";
                JasperReport  jr=JasperCompileManager.compileReport(reportsource);
                Map<String,Object> params = new HashMap<String, Object>();
                params.put("title1","title2");
                
                JasperPrint jp= JasperFillManager.fillReport(jr,params,datasource);
                //JasperViewer.viewReport(jp);
                
                JFrame frame = new JFrame("Reports");
                frame.getContentPane().add(new JRViewer(jp));
                frame.pack();
                frame.setSize(1000, 650);
                frame.setLocationRelativeTo(this);
                frame.setVisible(true);
                
            }
            catch(Exception e)
            {
                JOptionPane.showMessageDialog(null,"No record on table . to be displayed...Please Search record before trying generating report\n If Problem persist contact adminstratior ");
                
                //JOptionPane.showMessageDialog(null,e);
            }
                         
                     }
            
        
        
        
    }//GEN-LAST:event_btnReportsActionPerformed

    private void txtSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(rpt_Anlyz_Totals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(rpt_Anlyz_Totals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(rpt_Anlyz_Totals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(rpt_Anlyz_Totals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new rpt_Anlyz_Totals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnReports;
    private javax.swing.JComboBox cboCrime;
    private javax.swing.JComboBox cboLocations;
    private javax.swing.JComboBox cboSelect;
    private com.toedter.calendar.JDateChooser dateFrom;
    private com.toedter.calendar.JDateChooser dateTo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel pnlSuspectID;
    private javax.swing.JPanel pnldisp;
    private javax.swing.JTable tblSearch;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
